#!/usr/bin/env bash
# configure-macos.sh - macOS build configuration script for Proton
#

set -euo pipefail

SRCDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_BUILD_NAME="proton-macos-localbuild"

COLOR_ERR=""
COLOR_STAT=""
COLOR_INFO=""
COLOR_CLEAR=""
if [[ $(tput colors 2>/dev/null || echo 0) -gt 0 ]]; then
  COLOR_ERR=$'\e[31;1m'
  COLOR_STAT=$'\e[32;1m'
  COLOR_INFO=$'\e[30;1m'
  COLOR_CLEAR=$'\e[0m'
fi

err()  { echo >&2 "${COLOR_ERR}!!${COLOR_CLEAR} $*"; }
stat() { echo >&2 "${COLOR_STAT}::${COLOR_CLEAR} $*"; }
info() { echo >&2 "${COLOR_INFO}::${COLOR_CLEAR} $*"; }
die()  { err "$@"; exit 1; }

# Check macOS host
if [[ "$(uname -s)" != "Darwin" ]]; then
  die "configure-macos.sh must be run on macOS (Darwin)."
fi

# Check required build tools
stat "Checking build dependencies for macOS..."
command -v make >/dev/null 2>&1 || die "GNU Make is required."
command -v clang >/dev/null 2>&1 || die "Apple Clang is required (install Xcode command line tools)."
xcrun --show-sdk-path >/dev/null 2>&1 || die "macOS SDK is missing."

# Check mingw-w64 cross-compilers if present
if command -v x86_64-w64-mingw32-gcc >/dev/null 2>&1; then
  info "Found x86_64-w64-mingw32-gcc cross-compiler."
else
  info "Notice: x86_64-w64-mingw32-gcc not found in PATH. PE targets will require Homebrew mingw-w64."
fi

# Argument parsing
BUILD_NAME="$DEFAULT_BUILD_NAME"
TARGET_ARCH="x86_64"
DEPLOYMENT_TARGET="11.0"
ENABLE_CCACHE="0"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --build-name=*)
      BUILD_NAME="${1#*=}"
      ;;
    --target-arch=*)
      TARGET_ARCH="${1#*=}"
      ;;
    --deployment-target=*)
      DEPLOYMENT_TARGET="${1#*=}"
      ;;
    --enable-ccache)
      ENABLE_CCACHE="1"
      ;;
    --help)
      echo "Usage: $0 [options]"
      echo "  --build-name=<name>         Set build name (default: $DEFAULT_BUILD_NAME)"
      echo "  --target-arch=<arch>        Set target arch: x86_64 (default) or arm64"
      echo "  --deployment-target=<ver>   Set macOS deployment target (default: 11.0)"
      echo "  --enable-ccache             Enable ccache if installed"
      echo "  --help                      Show this help message"
      exit 0
      ;;
    *)
      die "Unknown option: $1"
      ;;
  esac
  shift
done

MACOS_SDK_PATH="$(xcrun --show-sdk-path)"
MAKEFILE="Makefile"

stat "Configuring Proton for macOS ($TARGET_ARCH)..."
stat "  SDK Path: $MACOS_SDK_PATH"
stat "  Deployment Target: $DEPLOYMENT_TARGET"

rm -f "$MAKEFILE"

cat << EOF > "$MAKEFILE"
# Generated by configure-macos.sh on $(date -u)
SRCDIR                   := $SRCDIR
BUILD_NAME               := $BUILD_NAME
INTERNAL_TOOL_NAME       := ${BUILD_NAME}-proton
TARGET_OS                := macos
TARGET_ARCH              := $TARGET_ARCH
CONTAINER_ENGINE         := none
ROOTLESS_CONTAINER       := 0
MACOS_SDK_PATH           := $MACOS_SDK_PATH
MACOS_DEPLOYMENT_TARGET  := $DEPLOYMENT_TARGET
ENABLE_CCACHE            := $ENABLE_CCACHE

include \$(SRCDIR)/Makefile.in
EOF

chmod +x "$MAKEFILE" 2>/dev/null || true
stat "Successfully created $MAKEFILE. Run 'make' to start the macOS build."
