#version 460
#extension GL_EXT_ray_tracing : enable
rayPayloadInEXT vec4 payloadIn;                             // ERROR, rayPayloadIn unsupported in this stage
rayPayloadEXT vec4 payload;                                 // ERROR, rayPayload unsuppoted in this stage
uniform accelerationStructureEXT accEXT;
void main()
{
    float e12 = gl_HitTEXT;                                 // ERROR, unsupported builtin in stage
    float e13 = gl_HitKindEXT;                              // ERROR, unsupported builtin in stage
    traceRayEXT(accEXT, 0, 0, 1, 1, 0, vec3(0.0f), 0.5f, vec3(1.0f), 0.75f, 0); // ERROR, unsupported
}
