typedef struct winVREvent_t_113b winVREvent_t_113b;
extern void struct_VREvent_t_113b_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_113b winVRControllerState001_t_113b;
extern void struct_VRControllerState001_t_113b_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_113b winRenderModel_TextureMap_t_113b;
extern struct winRenderModel_TextureMap_t_113b *struct_RenderModel_TextureMap_t_113b_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_113b_unwrap(winRenderModel_TextureMap_t_113b *w);
typedef struct winRenderModel_t_113b winRenderModel_t_113b;
extern struct winRenderModel_t_113b *struct_RenderModel_t_113b_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_113b_unwrap(winRenderModel_t_113b *w);
typedef struct winVREvent_t_1017 winVREvent_t_1017;
extern void struct_VREvent_t_1017_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_1017 winVRControllerState001_t_1017;
extern void struct_VRControllerState001_t_1017_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_1017 winRenderModel_TextureMap_t_1017;
extern struct winRenderModel_TextureMap_t_1017 *struct_RenderModel_TextureMap_t_1017_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1017_unwrap(winRenderModel_TextureMap_t_1017 *w);
typedef struct winRenderModel_t_1017 winRenderModel_t_1017;
extern struct winRenderModel_t_1017 *struct_RenderModel_t_1017_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1017_unwrap(winRenderModel_t_1017 *w);
typedef struct winVREvent_t_1016 winVREvent_t_1016;
extern void struct_VREvent_t_1016_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_1016 winVRControllerState001_t_1016;
extern void struct_VRControllerState001_t_1016_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_1016 winRenderModel_TextureMap_t_1016;
extern struct winRenderModel_TextureMap_t_1016 *struct_RenderModel_TextureMap_t_1016_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1016_unwrap(winRenderModel_TextureMap_t_1016 *w);
typedef struct winRenderModel_t_1016 winRenderModel_t_1016;
extern struct winRenderModel_t_1016 *struct_RenderModel_t_1016_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1016_unwrap(winRenderModel_t_1016 *w);
typedef struct winVREvent_t_1015 winVREvent_t_1015;
extern void struct_VREvent_t_1015_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_1015 winVRControllerState001_t_1015;
extern void struct_VRControllerState001_t_1015_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_1015 winRenderModel_TextureMap_t_1015;
extern struct winRenderModel_TextureMap_t_1015 *struct_RenderModel_TextureMap_t_1015_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1015_unwrap(winRenderModel_TextureMap_t_1015 *w);
typedef struct winRenderModel_t_1015 winRenderModel_t_1015;
extern struct winRenderModel_t_1015 *struct_RenderModel_t_1015_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1015_unwrap(winRenderModel_t_1015 *w);
typedef struct winVREvent_t_1014 winVREvent_t_1014;
extern void struct_VREvent_t_1014_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_1014 winVRControllerState001_t_1014;
extern void struct_VRControllerState001_t_1014_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_1014 winRenderModel_TextureMap_t_1014;
extern struct winRenderModel_TextureMap_t_1014 *struct_RenderModel_TextureMap_t_1014_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1014_unwrap(winRenderModel_TextureMap_t_1014 *w);
typedef struct winRenderModel_t_1014 winRenderModel_t_1014;
extern struct winRenderModel_t_1014 *struct_RenderModel_t_1014_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1014_unwrap(winRenderModel_t_1014 *w);
typedef struct winVREvent_t_1013 winVREvent_t_1013;
extern void struct_VREvent_t_1013_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_1013 winVRControllerState001_t_1013;
extern void struct_VRControllerState001_t_1013_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_1013 winRenderModel_TextureMap_t_1013;
extern struct winRenderModel_TextureMap_t_1013 *struct_RenderModel_TextureMap_t_1013_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1013_unwrap(winRenderModel_TextureMap_t_1013 *w);
typedef struct winRenderModel_t_1013 winRenderModel_t_1013;
extern struct winRenderModel_t_1013 *struct_RenderModel_t_1013_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1013_unwrap(winRenderModel_t_1013 *w);
typedef struct winVREvent_t_1012 winVREvent_t_1012;
extern void struct_VREvent_t_1012_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_1012 winVRControllerState001_t_1012;
extern void struct_VRControllerState001_t_1012_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_1012 winRenderModel_TextureMap_t_1012;
extern struct winRenderModel_TextureMap_t_1012 *struct_RenderModel_TextureMap_t_1012_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1012_unwrap(winRenderModel_TextureMap_t_1012 *w);
typedef struct winRenderModel_t_1012 winRenderModel_t_1012;
extern struct winRenderModel_t_1012 *struct_RenderModel_t_1012_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1012_unwrap(winRenderModel_t_1012 *w);
typedef struct winVREvent_t_1011 winVREvent_t_1011;
extern void struct_VREvent_t_1011_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_1011 winVRControllerState001_t_1011;
extern void struct_VRControllerState001_t_1011_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_1011 winRenderModel_TextureMap_t_1011;
extern struct winRenderModel_TextureMap_t_1011 *struct_RenderModel_TextureMap_t_1011_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1011_unwrap(winRenderModel_TextureMap_t_1011 *w);
typedef struct winRenderModel_t_1011 winRenderModel_t_1011;
extern struct winRenderModel_t_1011 *struct_RenderModel_t_1011_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1011_unwrap(winRenderModel_t_1011 *w);
typedef struct winVREvent_t_1010 winVREvent_t_1010;
extern void struct_VREvent_t_1010_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_1010 winVRControllerState001_t_1010;
extern void struct_VRControllerState001_t_1010_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_1010 winRenderModel_TextureMap_t_1010;
extern struct winRenderModel_TextureMap_t_1010 *struct_RenderModel_TextureMap_t_1010_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1010_unwrap(winRenderModel_TextureMap_t_1010 *w);
typedef struct winRenderModel_t_1010 winRenderModel_t_1010;
extern struct winRenderModel_t_1010 *struct_RenderModel_t_1010_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1010_unwrap(winRenderModel_t_1010 *w);
typedef struct winVREvent_t_109 winVREvent_t_109;
extern void struct_VREvent_t_109_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_109 winVRControllerState001_t_109;
extern void struct_VRControllerState001_t_109_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_109 winRenderModel_TextureMap_t_109;
extern struct winRenderModel_TextureMap_t_109 *struct_RenderModel_TextureMap_t_109_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_109_unwrap(winRenderModel_TextureMap_t_109 *w);
typedef struct winRenderModel_t_109 winRenderModel_t_109;
extern struct winRenderModel_t_109 *struct_RenderModel_t_109_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_109_unwrap(winRenderModel_t_109 *w);
typedef struct winVREvent_t_108 winVREvent_t_108;
extern void struct_VREvent_t_108_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_108 winVRControllerState001_t_108;
extern void struct_VRControllerState001_t_108_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_108 winRenderModel_TextureMap_t_108;
extern struct winRenderModel_TextureMap_t_108 *struct_RenderModel_TextureMap_t_108_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_108_unwrap(winRenderModel_TextureMap_t_108 *w);
typedef struct winRenderModel_t_108 winRenderModel_t_108;
extern struct winRenderModel_t_108 *struct_RenderModel_t_108_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_108_unwrap(winRenderModel_t_108 *w);
typedef struct winVREvent_t_107 winVREvent_t_107;
extern void struct_VREvent_t_107_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_107 winVRControllerState001_t_107;
extern void struct_VRControllerState001_t_107_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_107 winRenderModel_TextureMap_t_107;
extern struct winRenderModel_TextureMap_t_107 *struct_RenderModel_TextureMap_t_107_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_107_unwrap(winRenderModel_TextureMap_t_107 *w);
typedef struct winRenderModel_t_107 winRenderModel_t_107;
extern struct winRenderModel_t_107 *struct_RenderModel_t_107_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_107_unwrap(winRenderModel_t_107 *w);
typedef struct winVREvent_t_106 winVREvent_t_106;
extern void struct_VREvent_t_106_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_106 winVRControllerState001_t_106;
extern void struct_VRControllerState001_t_106_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_106 winRenderModel_TextureMap_t_106;
extern struct winRenderModel_TextureMap_t_106 *struct_RenderModel_TextureMap_t_106_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_106_unwrap(winRenderModel_TextureMap_t_106 *w);
typedef struct winRenderModel_t_106 winRenderModel_t_106;
extern struct winRenderModel_t_106 *struct_RenderModel_t_106_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_106_unwrap(winRenderModel_t_106 *w);
typedef struct winVREvent_t_105 winVREvent_t_105;
extern void struct_VREvent_t_105_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_105 winVRControllerState001_t_105;
extern void struct_VRControllerState001_t_105_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_105 winRenderModel_TextureMap_t_105;
extern struct winRenderModel_TextureMap_t_105 *struct_RenderModel_TextureMap_t_105_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_105_unwrap(winRenderModel_TextureMap_t_105 *w);
typedef struct winRenderModel_t_105 winRenderModel_t_105;
extern struct winRenderModel_t_105 *struct_RenderModel_t_105_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_105_unwrap(winRenderModel_t_105 *w);
typedef struct winVREvent_t_104 winVREvent_t_104;
extern void struct_VREvent_t_104_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_104 winVRControllerState001_t_104;
extern void struct_VRControllerState001_t_104_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_104 winRenderModel_TextureMap_t_104;
extern struct winRenderModel_TextureMap_t_104 *struct_RenderModel_TextureMap_t_104_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_104_unwrap(winRenderModel_TextureMap_t_104 *w);
typedef struct winRenderModel_t_104 winRenderModel_t_104;
extern struct winRenderModel_t_104 *struct_RenderModel_t_104_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_104_unwrap(winRenderModel_t_104 *w);
typedef struct winVREvent_t_103a winVREvent_t_103a;
extern void struct_VREvent_t_103a_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_103a winVRControllerState001_t_103a;
extern void struct_VRControllerState001_t_103a_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_103a winRenderModel_TextureMap_t_103a;
extern struct winRenderModel_TextureMap_t_103a *struct_RenderModel_TextureMap_t_103a_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_103a_unwrap(winRenderModel_TextureMap_t_103a *w);
typedef struct winRenderModel_t_103a winRenderModel_t_103a;
extern struct winRenderModel_t_103a *struct_RenderModel_t_103a_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_103a_unwrap(winRenderModel_t_103a *w);
typedef struct winVREvent_t_103 winVREvent_t_103;
extern void struct_VREvent_t_103_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_103 winVRControllerState001_t_103;
extern void struct_VRControllerState001_t_103_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_103 winRenderModel_TextureMap_t_103;
extern struct winRenderModel_TextureMap_t_103 *struct_RenderModel_TextureMap_t_103_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_103_unwrap(winRenderModel_TextureMap_t_103 *w);
typedef struct winRenderModel_t_103 winRenderModel_t_103;
extern struct winRenderModel_t_103 *struct_RenderModel_t_103_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_103_unwrap(winRenderModel_t_103 *w);
typedef struct winVREvent_t_102 winVREvent_t_102;
extern void struct_VREvent_t_102_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_102 winVRControllerState001_t_102;
extern void struct_VRControllerState001_t_102_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_102 winRenderModel_TextureMap_t_102;
extern struct winRenderModel_TextureMap_t_102 *struct_RenderModel_TextureMap_t_102_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_102_unwrap(winRenderModel_TextureMap_t_102 *w);
typedef struct winRenderModel_t_102 winRenderModel_t_102;
extern struct winRenderModel_t_102 *struct_RenderModel_t_102_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_102_unwrap(winRenderModel_t_102 *w);
typedef struct winVREvent_t_101 winVREvent_t_101;
extern void struct_VREvent_t_101_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_101 winVRControllerState001_t_101;
extern void struct_VRControllerState001_t_101_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_101 winRenderModel_TextureMap_t_101;
extern struct winRenderModel_TextureMap_t_101 *struct_RenderModel_TextureMap_t_101_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_101_unwrap(winRenderModel_TextureMap_t_101 *w);
typedef struct winRenderModel_t_101 winRenderModel_t_101;
extern struct winRenderModel_t_101 *struct_RenderModel_t_101_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_101_unwrap(winRenderModel_t_101 *w);
typedef struct winVREvent_t_100 winVREvent_t_100;
extern void struct_VREvent_t_100_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_100 winVRControllerState001_t_100;
extern void struct_VRControllerState001_t_100_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_100 winRenderModel_TextureMap_t_100;
extern struct winRenderModel_TextureMap_t_100 *struct_RenderModel_TextureMap_t_100_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_100_unwrap(winRenderModel_TextureMap_t_100 *w);
typedef struct winRenderModel_t_100 winRenderModel_t_100;
extern struct winRenderModel_t_100 *struct_RenderModel_t_100_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_100_unwrap(winRenderModel_t_100 *w);
typedef struct winVREvent_t_0920 winVREvent_t_0920;
extern void struct_VREvent_t_0920_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_0920 winVRControllerState001_t_0920;
extern void struct_VRControllerState001_t_0920_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_0920 winRenderModel_TextureMap_t_0920;
extern struct winRenderModel_TextureMap_t_0920 *struct_RenderModel_TextureMap_t_0920_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_0920_unwrap(winRenderModel_TextureMap_t_0920 *w);
typedef struct winRenderModel_t_0920 winRenderModel_t_0920;
extern struct winRenderModel_t_0920 *struct_RenderModel_t_0920_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_0920_unwrap(winRenderModel_t_0920 *w);
typedef struct winVREvent_t_0919 winVREvent_t_0919;
extern void struct_VREvent_t_0919_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_0919 winVRControllerState001_t_0919;
extern void struct_VRControllerState001_t_0919_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_0919 winRenderModel_TextureMap_t_0919;
extern struct winRenderModel_TextureMap_t_0919 *struct_RenderModel_TextureMap_t_0919_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_0919_unwrap(winRenderModel_TextureMap_t_0919 *w);
typedef struct winRenderModel_t_0919 winRenderModel_t_0919;
extern struct winRenderModel_t_0919 *struct_RenderModel_t_0919_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_0919_unwrap(winRenderModel_t_0919 *w);
typedef struct winVREvent_t_0918 winVREvent_t_0918;
extern void struct_VREvent_t_0918_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_0918 winVRControllerState001_t_0918;
extern void struct_VRControllerState001_t_0918_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_0918 winRenderModel_TextureMap_t_0918;
extern struct winRenderModel_TextureMap_t_0918 *struct_RenderModel_TextureMap_t_0918_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_0918_unwrap(winRenderModel_TextureMap_t_0918 *w);
typedef struct winRenderModel_t_0918 winRenderModel_t_0918;
extern struct winRenderModel_t_0918 *struct_RenderModel_t_0918_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_0918_unwrap(winRenderModel_t_0918 *w);
typedef struct winVREvent_t_0917 winVREvent_t_0917;
extern void struct_VREvent_t_0917_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_0917 winVRControllerState001_t_0917;
extern void struct_VRControllerState001_t_0917_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_0917 winRenderModel_TextureMap_t_0917;
extern struct winRenderModel_TextureMap_t_0917 *struct_RenderModel_TextureMap_t_0917_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_0917_unwrap(winRenderModel_TextureMap_t_0917 *w);
typedef struct winRenderModel_t_0917 winRenderModel_t_0917;
extern struct winRenderModel_t_0917 *struct_RenderModel_t_0917_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_0917_unwrap(winRenderModel_t_0917 *w);
typedef struct winVREvent_t_0916 winVREvent_t_0916;
extern void struct_VREvent_t_0916_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_0916 winVRControllerState001_t_0916;
extern void struct_VRControllerState001_t_0916_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_0916 winRenderModel_TextureMap_t_0916;
extern struct winRenderModel_TextureMap_t_0916 *struct_RenderModel_TextureMap_t_0916_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_0916_unwrap(winRenderModel_TextureMap_t_0916 *w);
typedef struct winRenderModel_t_0916 winRenderModel_t_0916;
extern struct winRenderModel_t_0916 *struct_RenderModel_t_0916_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_0916_unwrap(winRenderModel_t_0916 *w);
typedef struct winVREvent_t_0915 winVREvent_t_0915;
extern void struct_VREvent_t_0915_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_0915 winVRControllerState001_t_0915;
extern void struct_VRControllerState001_t_0915_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_0915 winRenderModel_TextureMap_t_0915;
extern struct winRenderModel_TextureMap_t_0915 *struct_RenderModel_TextureMap_t_0915_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_0915_unwrap(winRenderModel_TextureMap_t_0915 *w);
typedef struct winRenderModel_t_0915 winRenderModel_t_0915;
extern struct winRenderModel_t_0915 *struct_RenderModel_t_0915_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_0915_unwrap(winRenderModel_t_0915 *w);
typedef struct winVREvent_t_0914 winVREvent_t_0914;
extern void struct_VREvent_t_0914_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_0914 winVRControllerState001_t_0914;
extern void struct_VRControllerState001_t_0914_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_0914 winRenderModel_TextureMap_t_0914;
extern struct winRenderModel_TextureMap_t_0914 *struct_RenderModel_TextureMap_t_0914_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_0914_unwrap(winRenderModel_TextureMap_t_0914 *w);
typedef struct winRenderModel_t_0914 winRenderModel_t_0914;
extern struct winRenderModel_t_0914 *struct_RenderModel_t_0914_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_0914_unwrap(winRenderModel_t_0914 *w);
typedef struct winVREvent_t_0913 winVREvent_t_0913;
extern void struct_VREvent_t_0913_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_0913 winVRControllerState001_t_0913;
extern void struct_VRControllerState001_t_0913_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_0913 winRenderModel_TextureMap_t_0913;
extern struct winRenderModel_TextureMap_t_0913 *struct_RenderModel_TextureMap_t_0913_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_0913_unwrap(winRenderModel_TextureMap_t_0913 *w);
typedef struct winRenderModel_t_0913 winRenderModel_t_0913;
extern struct winRenderModel_t_0913 *struct_RenderModel_t_0913_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_0913_unwrap(winRenderModel_t_0913 *w);
typedef struct winVREvent_t_0912 winVREvent_t_0912;
extern void struct_VREvent_t_0912_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_0912 winVRControllerState001_t_0912;
extern void struct_VRControllerState001_t_0912_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_0912 winRenderModel_TextureMap_t_0912;
extern struct winRenderModel_TextureMap_t_0912 *struct_RenderModel_TextureMap_t_0912_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_0912_unwrap(winRenderModel_TextureMap_t_0912 *w);
typedef struct winRenderModel_t_0912 winRenderModel_t_0912;
extern struct winRenderModel_t_0912 *struct_RenderModel_t_0912_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_0912_unwrap(winRenderModel_t_0912 *w);
typedef struct winRenderModel_TextureMap_t_0910 winRenderModel_TextureMap_t_0910;
extern struct winRenderModel_TextureMap_t_0910 *struct_RenderModel_TextureMap_t_0910_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_0910_unwrap(winRenderModel_TextureMap_t_0910 *w);
typedef struct winRenderModel_t_0910 winRenderModel_t_0910;
extern struct winRenderModel_t_0910 *struct_RenderModel_t_0910_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_0910_unwrap(winRenderModel_t_0910 *w);
typedef struct winVREvent_t_0910 winVREvent_t_0910;
extern void struct_VREvent_t_0910_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_0910 winVRControllerState001_t_0910;
extern void struct_VRControllerState001_t_0910_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_099 winRenderModel_TextureMap_t_099;
extern struct winRenderModel_TextureMap_t_099 *struct_RenderModel_TextureMap_t_099_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_099_unwrap(winRenderModel_TextureMap_t_099 *w);
typedef struct winRenderModel_t_099 winRenderModel_t_099;
extern struct winRenderModel_t_099 *struct_RenderModel_t_099_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_099_unwrap(winRenderModel_t_099 *w);
typedef struct winVREvent_t_099 winVREvent_t_099;
extern void struct_VREvent_t_099_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_099 winVRControllerState001_t_099;
extern void struct_VRControllerState001_t_099_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_098 winRenderModel_TextureMap_t_098;
extern struct winRenderModel_TextureMap_t_098 *struct_RenderModel_TextureMap_t_098_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_098_unwrap(winRenderModel_TextureMap_t_098 *w);
typedef struct winRenderModel_t_098 winRenderModel_t_098;
extern struct winRenderModel_t_098 *struct_RenderModel_t_098_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_098_unwrap(winRenderModel_t_098 *w);
typedef struct winVREvent_t_098 winVREvent_t_098;
extern void struct_VREvent_t_098_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_098 winVRControllerState001_t_098;
extern void struct_VRControllerState001_t_098_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_097 winRenderModel_TextureMap_t_097;
extern struct winRenderModel_TextureMap_t_097 *struct_RenderModel_TextureMap_t_097_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_097_unwrap(winRenderModel_TextureMap_t_097 *w);
typedef struct winRenderModel_t_097 winRenderModel_t_097;
extern struct winRenderModel_t_097 *struct_RenderModel_t_097_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_097_unwrap(winRenderModel_t_097 *w);
typedef struct winVREvent_t_097 winVREvent_t_097;
extern void struct_VREvent_t_097_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_097 winVRControllerState001_t_097;
extern void struct_VRControllerState001_t_097_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_096 winRenderModel_TextureMap_t_096;
extern struct winRenderModel_TextureMap_t_096 *struct_RenderModel_TextureMap_t_096_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_096_unwrap(winRenderModel_TextureMap_t_096 *w);
typedef struct winRenderModel_t_096 winRenderModel_t_096;
extern struct winRenderModel_t_096 *struct_RenderModel_t_096_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_096_unwrap(winRenderModel_t_096 *w);
typedef struct winVREvent_t_096 winVREvent_t_096;
extern void struct_VREvent_t_096_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_096 winVRControllerState001_t_096;
extern void struct_VRControllerState001_t_096_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_094 winRenderModel_TextureMap_t_094;
extern struct winRenderModel_TextureMap_t_094 *struct_RenderModel_TextureMap_t_094_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_094_unwrap(winRenderModel_TextureMap_t_094 *w);
typedef struct winRenderModel_t_094 winRenderModel_t_094;
extern struct winRenderModel_t_094 *struct_RenderModel_t_094_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_094_unwrap(winRenderModel_t_094 *w);
typedef struct winVREvent_t_094 winVREvent_t_094;
extern void struct_VREvent_t_094_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_094 winVRControllerState001_t_094;
extern void struct_VRControllerState001_t_094_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_093 winRenderModel_TextureMap_t_093;
extern struct winRenderModel_TextureMap_t_093 *struct_RenderModel_TextureMap_t_093_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_093_unwrap(winRenderModel_TextureMap_t_093 *w);
typedef struct winRenderModel_t_093 winRenderModel_t_093;
extern struct winRenderModel_t_093 *struct_RenderModel_t_093_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_093_unwrap(winRenderModel_t_093 *w);
typedef struct winVREvent_t_093 winVREvent_t_093;
extern void struct_VREvent_t_093_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_093 winVRControllerState001_t_093;
extern void struct_VRControllerState001_t_093_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_092 winRenderModel_TextureMap_t_092;
extern struct winRenderModel_TextureMap_t_092 *struct_RenderModel_TextureMap_t_092_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_092_unwrap(winRenderModel_TextureMap_t_092 *w);
typedef struct winRenderModel_t_092 winRenderModel_t_092;
extern struct winRenderModel_t_092 *struct_RenderModel_t_092_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_092_unwrap(winRenderModel_t_092 *w);
typedef struct winVREvent_t_092 winVREvent_t_092;
extern void struct_VREvent_t_092_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_092 winVRControllerState001_t_092;
extern void struct_VRControllerState001_t_092_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_091 winRenderModel_TextureMap_t_091;
extern struct winRenderModel_TextureMap_t_091 *struct_RenderModel_TextureMap_t_091_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_091_unwrap(winRenderModel_TextureMap_t_091 *w);
typedef struct winRenderModel_t_091 winRenderModel_t_091;
extern struct winRenderModel_t_091 *struct_RenderModel_t_091_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_091_unwrap(winRenderModel_t_091 *w);
typedef struct winVREvent_t_091 winVREvent_t_091;
extern void struct_VREvent_t_091_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_091 winVRControllerState001_t_091;
extern void struct_VRControllerState001_t_091_lin_to_win(void *l, void *w);
typedef struct winRenderModel_TextureMap_t_090 winRenderModel_TextureMap_t_090;
extern struct winRenderModel_TextureMap_t_090 *struct_RenderModel_TextureMap_t_090_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_090_unwrap(winRenderModel_TextureMap_t_090 *w);
typedef struct winRenderModel_t_090 winRenderModel_t_090;
extern struct winRenderModel_t_090 *struct_RenderModel_t_090_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_090_unwrap(winRenderModel_t_090 *w);
typedef struct winVREvent_t_090 winVREvent_t_090;
extern void struct_VREvent_t_090_lin_to_win(void *l, void *w);
typedef struct winVRControllerState001_t_090 winVRControllerState001_t_090;
extern void struct_VRControllerState001_t_090_lin_to_win(void *l, void *w);
