typedef struct winVREvent_t_1819 winVREvent_t_1819;
extern void struct_VREvent_t_1819_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_1819_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_1819 winVRControllerState001_t_1819;
extern void struct_VRControllerState001_t_1819_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_1819_win_to_lin(void *w, void *l);
typedef struct winCameraVideoStreamFrameHeader_t_1819 winCameraVideoStreamFrameHeader_t_1819;
extern void struct_CameraVideoStreamFrameHeader_t_1819_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_CameraVideoStreamFrameHeader_t_1819_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_1819 winRenderModel_TextureMap_t_1819;
extern void struct_RenderModel_TextureMap_t_1819_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_1819_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_1819 *struct_RenderModel_TextureMap_t_1819_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1819_unwrap(winRenderModel_TextureMap_t_1819 *w);
typedef struct winRenderModel_t_1819 winRenderModel_t_1819;
extern void struct_RenderModel_t_1819_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_1819_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_1819 *struct_RenderModel_t_1819_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1819_unwrap(winRenderModel_t_1819 *w);
typedef struct winInputAnalogActionData_t_1819 winInputAnalogActionData_t_1819;
extern void struct_InputAnalogActionData_t_1819_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputAnalogActionData_t_1819_win_to_lin(void *w, void *l);
typedef struct winInputDigitalActionData_t_1819 winInputDigitalActionData_t_1819;
extern void struct_InputDigitalActionData_t_1819_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputDigitalActionData_t_1819_win_to_lin(void *w, void *l);
typedef struct winInputPoseActionData_t_1819 winInputPoseActionData_t_1819;
extern void struct_InputPoseActionData_t_1819_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputPoseActionData_t_1819_win_to_lin(void *w, void *l);
typedef struct winInputSkeletalActionData_t_1819 winInputSkeletalActionData_t_1819;
extern void struct_InputSkeletalActionData_t_1819_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputSkeletalActionData_t_1819_win_to_lin(void *w, void *l);
typedef struct winVREvent_t_1715 winVREvent_t_1715;
extern void struct_VREvent_t_1715_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_1715_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_1715 winVRControllerState001_t_1715;
extern void struct_VRControllerState001_t_1715_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_1715_win_to_lin(void *w, void *l);
typedef struct winCameraVideoStreamFrameHeader_t_1715 winCameraVideoStreamFrameHeader_t_1715;
extern void struct_CameraVideoStreamFrameHeader_t_1715_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_CameraVideoStreamFrameHeader_t_1715_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_1715 winRenderModel_TextureMap_t_1715;
extern void struct_RenderModel_TextureMap_t_1715_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_1715_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_1715 *struct_RenderModel_TextureMap_t_1715_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1715_unwrap(winRenderModel_TextureMap_t_1715 *w);
typedef struct winRenderModel_t_1715 winRenderModel_t_1715;
extern void struct_RenderModel_t_1715_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_1715_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_1715 *struct_RenderModel_t_1715_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1715_unwrap(winRenderModel_t_1715 *w);
typedef struct winInputAnalogActionData_t_1715 winInputAnalogActionData_t_1715;
extern void struct_InputAnalogActionData_t_1715_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputAnalogActionData_t_1715_win_to_lin(void *w, void *l);
typedef struct winInputDigitalActionData_t_1715 winInputDigitalActionData_t_1715;
extern void struct_InputDigitalActionData_t_1715_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputDigitalActionData_t_1715_win_to_lin(void *w, void *l);
typedef struct winInputPoseActionData_t_1715 winInputPoseActionData_t_1715;
extern void struct_InputPoseActionData_t_1715_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputPoseActionData_t_1715_win_to_lin(void *w, void *l);
typedef struct winInputSkeletalActionData_t_1715 winInputSkeletalActionData_t_1715;
extern void struct_InputSkeletalActionData_t_1715_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputSkeletalActionData_t_1715_win_to_lin(void *w, void *l);
typedef struct winVREvent_t_1610 winVREvent_t_1610;
extern void struct_VREvent_t_1610_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_1610_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_1610 winVRControllerState001_t_1610;
extern void struct_VRControllerState001_t_1610_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_1610_win_to_lin(void *w, void *l);
typedef struct winCameraVideoStreamFrameHeader_t_1610 winCameraVideoStreamFrameHeader_t_1610;
extern void struct_CameraVideoStreamFrameHeader_t_1610_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_CameraVideoStreamFrameHeader_t_1610_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_1610 winRenderModel_TextureMap_t_1610;
extern void struct_RenderModel_TextureMap_t_1610_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_1610_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_1610 *struct_RenderModel_TextureMap_t_1610_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1610_unwrap(winRenderModel_TextureMap_t_1610 *w);
typedef struct winRenderModel_t_1610 winRenderModel_t_1610;
extern void struct_RenderModel_t_1610_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_1610_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_1610 *struct_RenderModel_t_1610_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1610_unwrap(winRenderModel_t_1610 *w);
typedef struct winInputAnalogActionData_t_1610 winInputAnalogActionData_t_1610;
extern void struct_InputAnalogActionData_t_1610_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputAnalogActionData_t_1610_win_to_lin(void *w, void *l);
typedef struct winInputDigitalActionData_t_1610 winInputDigitalActionData_t_1610;
extern void struct_InputDigitalActionData_t_1610_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputDigitalActionData_t_1610_win_to_lin(void *w, void *l);
typedef struct winInputPoseActionData_t_1610 winInputPoseActionData_t_1610;
extern void struct_InputPoseActionData_t_1610_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputPoseActionData_t_1610_win_to_lin(void *w, void *l);
typedef struct winInputSkeletalActionData_t_1610 winInputSkeletalActionData_t_1610;
extern void struct_InputSkeletalActionData_t_1610_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputSkeletalActionData_t_1610_win_to_lin(void *w, void *l);
typedef struct winVREvent_t_1517 winVREvent_t_1517;
extern void struct_VREvent_t_1517_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_1517_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_1517 winVRControllerState001_t_1517;
extern void struct_VRControllerState001_t_1517_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_1517_win_to_lin(void *w, void *l);
typedef struct winCameraVideoStreamFrameHeader_t_1517 winCameraVideoStreamFrameHeader_t_1517;
extern void struct_CameraVideoStreamFrameHeader_t_1517_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_CameraVideoStreamFrameHeader_t_1517_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_1517 winRenderModel_TextureMap_t_1517;
extern void struct_RenderModel_TextureMap_t_1517_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_1517_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_1517 *struct_RenderModel_TextureMap_t_1517_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1517_unwrap(winRenderModel_TextureMap_t_1517 *w);
typedef struct winRenderModel_t_1517 winRenderModel_t_1517;
extern void struct_RenderModel_t_1517_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_1517_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_1517 *struct_RenderModel_t_1517_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1517_unwrap(winRenderModel_t_1517 *w);
typedef struct winInputAnalogActionData_t_1517 winInputAnalogActionData_t_1517;
extern void struct_InputAnalogActionData_t_1517_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputAnalogActionData_t_1517_win_to_lin(void *w, void *l);
typedef struct winInputDigitalActionData_t_1517 winInputDigitalActionData_t_1517;
extern void struct_InputDigitalActionData_t_1517_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputDigitalActionData_t_1517_win_to_lin(void *w, void *l);
typedef struct winInputPoseActionData_t_1517 winInputPoseActionData_t_1517;
extern void struct_InputPoseActionData_t_1517_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputPoseActionData_t_1517_win_to_lin(void *w, void *l);
typedef struct winInputSkeletalActionData_t_1517 winInputSkeletalActionData_t_1517;
extern void struct_InputSkeletalActionData_t_1517_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputSkeletalActionData_t_1517_win_to_lin(void *w, void *l);
typedef struct winVREvent_t_1418 winVREvent_t_1418;
extern void struct_VREvent_t_1418_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_1418_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_1418 winVRControllerState001_t_1418;
extern void struct_VRControllerState001_t_1418_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_1418_win_to_lin(void *w, void *l);
typedef struct winCameraVideoStreamFrameHeader_t_1418 winCameraVideoStreamFrameHeader_t_1418;
extern void struct_CameraVideoStreamFrameHeader_t_1418_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_CameraVideoStreamFrameHeader_t_1418_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_1418 winRenderModel_TextureMap_t_1418;
extern void struct_RenderModel_TextureMap_t_1418_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_1418_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_1418 *struct_RenderModel_TextureMap_t_1418_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1418_unwrap(winRenderModel_TextureMap_t_1418 *w);
typedef struct winRenderModel_t_1418 winRenderModel_t_1418;
extern void struct_RenderModel_t_1418_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_1418_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_1418 *struct_RenderModel_t_1418_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1418_unwrap(winRenderModel_t_1418 *w);
typedef struct winInputAnalogActionData_t_1418 winInputAnalogActionData_t_1418;
extern void struct_InputAnalogActionData_t_1418_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputAnalogActionData_t_1418_win_to_lin(void *w, void *l);
typedef struct winInputDigitalActionData_t_1418 winInputDigitalActionData_t_1418;
extern void struct_InputDigitalActionData_t_1418_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputDigitalActionData_t_1418_win_to_lin(void *w, void *l);
typedef struct winInputPoseActionData_t_1418 winInputPoseActionData_t_1418;
extern void struct_InputPoseActionData_t_1418_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputPoseActionData_t_1418_win_to_lin(void *w, void *l);
typedef struct winInputSkeletalActionData_t_1418 winInputSkeletalActionData_t_1418;
extern void struct_InputSkeletalActionData_t_1418_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputSkeletalActionData_t_1418_win_to_lin(void *w, void *l);
typedef struct winVREvent_t_1322 winVREvent_t_1322;
extern void struct_VREvent_t_1322_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_1322_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_1322 winVRControllerState001_t_1322;
extern void struct_VRControllerState001_t_1322_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_1322_win_to_lin(void *w, void *l);
typedef struct winCameraVideoStreamFrameHeader_t_1322 winCameraVideoStreamFrameHeader_t_1322;
extern void struct_CameraVideoStreamFrameHeader_t_1322_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_CameraVideoStreamFrameHeader_t_1322_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_1322 winRenderModel_TextureMap_t_1322;
extern void struct_RenderModel_TextureMap_t_1322_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_1322_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_1322 *struct_RenderModel_TextureMap_t_1322_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1322_unwrap(winRenderModel_TextureMap_t_1322 *w);
typedef struct winRenderModel_t_1322 winRenderModel_t_1322;
extern void struct_RenderModel_t_1322_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_1322_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_1322 *struct_RenderModel_t_1322_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1322_unwrap(winRenderModel_t_1322 *w);
typedef struct winInputAnalogActionData_t_1322 winInputAnalogActionData_t_1322;
extern void struct_InputAnalogActionData_t_1322_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputAnalogActionData_t_1322_win_to_lin(void *w, void *l);
typedef struct winInputDigitalActionData_t_1322 winInputDigitalActionData_t_1322;
extern void struct_InputDigitalActionData_t_1322_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputDigitalActionData_t_1322_win_to_lin(void *w, void *l);
typedef struct winInputPoseActionData_t_1322 winInputPoseActionData_t_1322;
extern void struct_InputPoseActionData_t_1322_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputPoseActionData_t_1322_win_to_lin(void *w, void *l);
typedef struct winInputSkeletalActionData_t_1322 winInputSkeletalActionData_t_1322;
extern void struct_InputSkeletalActionData_t_1322_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputSkeletalActionData_t_1322_win_to_lin(void *w, void *l);
typedef struct winVREvent_t_1210 winVREvent_t_1210;
extern void struct_VREvent_t_1210_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_1210_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_1210 winVRControllerState001_t_1210;
extern void struct_VRControllerState001_t_1210_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_1210_win_to_lin(void *w, void *l);
typedef struct winCameraVideoStreamFrameHeader_t_1210 winCameraVideoStreamFrameHeader_t_1210;
extern void struct_CameraVideoStreamFrameHeader_t_1210_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_CameraVideoStreamFrameHeader_t_1210_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_1210 winRenderModel_TextureMap_t_1210;
extern void struct_RenderModel_TextureMap_t_1210_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_1210_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_1210 *struct_RenderModel_TextureMap_t_1210_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1210_unwrap(winRenderModel_TextureMap_t_1210 *w);
typedef struct winRenderModel_t_1210 winRenderModel_t_1210;
extern void struct_RenderModel_t_1210_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_1210_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_1210 *struct_RenderModel_t_1210_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1210_unwrap(winRenderModel_t_1210 *w);
typedef struct winInputAnalogActionData_t_1210 winInputAnalogActionData_t_1210;
extern void struct_InputAnalogActionData_t_1210_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputAnalogActionData_t_1210_win_to_lin(void *w, void *l);
typedef struct winInputDigitalActionData_t_1210 winInputDigitalActionData_t_1210;
extern void struct_InputDigitalActionData_t_1210_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputDigitalActionData_t_1210_win_to_lin(void *w, void *l);
typedef struct winInputPoseActionData_t_1210 winInputPoseActionData_t_1210;
extern void struct_InputPoseActionData_t_1210_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputPoseActionData_t_1210_win_to_lin(void *w, void *l);
typedef struct winInputSkeletalActionData_t_1210 winInputSkeletalActionData_t_1210;
extern void struct_InputSkeletalActionData_t_1210_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputSkeletalActionData_t_1210_win_to_lin(void *w, void *l);
typedef struct winVREvent_t_113b winVREvent_t_113b;
extern void struct_VREvent_t_113b_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_113b_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_113b winVRControllerState001_t_113b;
extern void struct_VRControllerState001_t_113b_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_113b_win_to_lin(void *w, void *l);
typedef struct winCameraVideoStreamFrameHeader_t_113b winCameraVideoStreamFrameHeader_t_113b;
extern void struct_CameraVideoStreamFrameHeader_t_113b_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_CameraVideoStreamFrameHeader_t_113b_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_113b winRenderModel_TextureMap_t_113b;
extern void struct_RenderModel_TextureMap_t_113b_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_113b_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_113b *struct_RenderModel_TextureMap_t_113b_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_113b_unwrap(winRenderModel_TextureMap_t_113b *w);
typedef struct winRenderModel_t_113b winRenderModel_t_113b;
extern void struct_RenderModel_t_113b_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_113b_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_113b *struct_RenderModel_t_113b_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_113b_unwrap(winRenderModel_t_113b *w);
typedef struct winInputAnalogActionData_t_113b winInputAnalogActionData_t_113b;
extern void struct_InputAnalogActionData_t_113b_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputAnalogActionData_t_113b_win_to_lin(void *w, void *l);
typedef struct winInputDigitalActionData_t_113b winInputDigitalActionData_t_113b;
extern void struct_InputDigitalActionData_t_113b_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputDigitalActionData_t_113b_win_to_lin(void *w, void *l);
typedef struct winInputPoseActionData_t_113b winInputPoseActionData_t_113b;
extern void struct_InputPoseActionData_t_113b_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputPoseActionData_t_113b_win_to_lin(void *w, void *l);
typedef struct winInputSkeletalActionData_t_113b winInputSkeletalActionData_t_113b;
extern void struct_InputSkeletalActionData_t_113b_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputSkeletalActionData_t_113b_win_to_lin(void *w, void *l);
typedef struct winVREvent_t_1017 winVREvent_t_1017;
extern void struct_VREvent_t_1017_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_1017_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_1017 winVRControllerState001_t_1017;
extern void struct_VRControllerState001_t_1017_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_1017_win_to_lin(void *w, void *l);
typedef struct winCameraVideoStreamFrameHeader_t_1017 winCameraVideoStreamFrameHeader_t_1017;
extern void struct_CameraVideoStreamFrameHeader_t_1017_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_CameraVideoStreamFrameHeader_t_1017_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_1017 winRenderModel_TextureMap_t_1017;
extern void struct_RenderModel_TextureMap_t_1017_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_1017_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_1017 *struct_RenderModel_TextureMap_t_1017_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1017_unwrap(winRenderModel_TextureMap_t_1017 *w);
typedef struct winRenderModel_t_1017 winRenderModel_t_1017;
extern void struct_RenderModel_t_1017_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_1017_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_1017 *struct_RenderModel_t_1017_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1017_unwrap(winRenderModel_t_1017 *w);
typedef struct winInputAnalogActionData_t_1017 winInputAnalogActionData_t_1017;
extern void struct_InputAnalogActionData_t_1017_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputAnalogActionData_t_1017_win_to_lin(void *w, void *l);
typedef struct winInputDigitalActionData_t_1017 winInputDigitalActionData_t_1017;
extern void struct_InputDigitalActionData_t_1017_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputDigitalActionData_t_1017_win_to_lin(void *w, void *l);
typedef struct winInputPoseActionData_t_1017 winInputPoseActionData_t_1017;
extern void struct_InputPoseActionData_t_1017_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputPoseActionData_t_1017_win_to_lin(void *w, void *l);
typedef struct winInputSkeletalActionData_t_1017 winInputSkeletalActionData_t_1017;
extern void struct_InputSkeletalActionData_t_1017_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputSkeletalActionData_t_1017_win_to_lin(void *w, void *l);
typedef struct winVREvent_t_1016 winVREvent_t_1016;
extern void struct_VREvent_t_1016_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_1016_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_1016 winVRControllerState001_t_1016;
extern void struct_VRControllerState001_t_1016_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_1016_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_1016 winRenderModel_TextureMap_t_1016;
extern void struct_RenderModel_TextureMap_t_1016_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_1016_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_1016 *struct_RenderModel_TextureMap_t_1016_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1016_unwrap(winRenderModel_TextureMap_t_1016 *w);
typedef struct winRenderModel_t_1016 winRenderModel_t_1016;
extern void struct_RenderModel_t_1016_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_1016_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_1016 *struct_RenderModel_t_1016_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1016_unwrap(winRenderModel_t_1016 *w);
typedef struct winInputAnalogActionData_t_1016 winInputAnalogActionData_t_1016;
extern void struct_InputAnalogActionData_t_1016_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputAnalogActionData_t_1016_win_to_lin(void *w, void *l);
typedef struct winInputDigitalActionData_t_1016 winInputDigitalActionData_t_1016;
extern void struct_InputDigitalActionData_t_1016_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputDigitalActionData_t_1016_win_to_lin(void *w, void *l);
typedef struct winInputPoseActionData_t_1016 winInputPoseActionData_t_1016;
extern void struct_InputPoseActionData_t_1016_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputPoseActionData_t_1016_win_to_lin(void *w, void *l);
typedef struct winInputSkeletalActionData_t_1016 winInputSkeletalActionData_t_1016;
extern void struct_InputSkeletalActionData_t_1016_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputSkeletalActionData_t_1016_win_to_lin(void *w, void *l);
typedef struct winVREvent_t_1015 winVREvent_t_1015;
extern void struct_VREvent_t_1015_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_1015_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_1015 winVRControllerState001_t_1015;
extern void struct_VRControllerState001_t_1015_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_1015_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_1015 winRenderModel_TextureMap_t_1015;
extern void struct_RenderModel_TextureMap_t_1015_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_1015_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_1015 *struct_RenderModel_TextureMap_t_1015_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1015_unwrap(winRenderModel_TextureMap_t_1015 *w);
typedef struct winRenderModel_t_1015 winRenderModel_t_1015;
extern void struct_RenderModel_t_1015_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_1015_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_1015 *struct_RenderModel_t_1015_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1015_unwrap(winRenderModel_t_1015 *w);
typedef struct winInputAnalogActionData_t_1015 winInputAnalogActionData_t_1015;
extern void struct_InputAnalogActionData_t_1015_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputAnalogActionData_t_1015_win_to_lin(void *w, void *l);
typedef struct winInputDigitalActionData_t_1015 winInputDigitalActionData_t_1015;
extern void struct_InputDigitalActionData_t_1015_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputDigitalActionData_t_1015_win_to_lin(void *w, void *l);
typedef struct winInputPoseActionData_t_1015 winInputPoseActionData_t_1015;
extern void struct_InputPoseActionData_t_1015_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_InputPoseActionData_t_1015_win_to_lin(void *w, void *l);
typedef struct winInputSkeletonActionData_t_1015 winInputSkeletonActionData_t_1015;
extern void struct_InputSkeletonActionData_t_1015_lin_to_win(void *l, void *w);
extern void struct_InputSkeletonActionData_t_1015_win_to_lin(void *w, void *l);
typedef struct winVREvent_t_1014 winVREvent_t_1014;
extern void struct_VREvent_t_1014_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_1014_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_1014 winVRControllerState001_t_1014;
extern void struct_VRControllerState001_t_1014_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_1014_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_1014 winRenderModel_TextureMap_t_1014;
extern void struct_RenderModel_TextureMap_t_1014_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_1014_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_1014 *struct_RenderModel_TextureMap_t_1014_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1014_unwrap(winRenderModel_TextureMap_t_1014 *w);
typedef struct winRenderModel_t_1014 winRenderModel_t_1014;
extern void struct_RenderModel_t_1014_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_1014_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_1014 *struct_RenderModel_t_1014_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1014_unwrap(winRenderModel_t_1014 *w);
typedef struct winVREvent_t_1013 winVREvent_t_1013;
extern void struct_VREvent_t_1013_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_1013_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_1013 winVRControllerState001_t_1013;
extern void struct_VRControllerState001_t_1013_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_1013_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_1013 winRenderModel_TextureMap_t_1013;
extern void struct_RenderModel_TextureMap_t_1013_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_1013_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_1013 *struct_RenderModel_TextureMap_t_1013_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1013_unwrap(winRenderModel_TextureMap_t_1013 *w);
typedef struct winRenderModel_t_1013 winRenderModel_t_1013;
extern void struct_RenderModel_t_1013_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_1013_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_1013 *struct_RenderModel_t_1013_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1013_unwrap(winRenderModel_t_1013 *w);
typedef struct winVREvent_t_1012 winVREvent_t_1012;
extern void struct_VREvent_t_1012_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_1012_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_1012 winVRControllerState001_t_1012;
extern void struct_VRControllerState001_t_1012_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_1012_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_1012 winRenderModel_TextureMap_t_1012;
extern void struct_RenderModel_TextureMap_t_1012_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_1012_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_1012 *struct_RenderModel_TextureMap_t_1012_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1012_unwrap(winRenderModel_TextureMap_t_1012 *w);
typedef struct winRenderModel_t_1012 winRenderModel_t_1012;
extern void struct_RenderModel_t_1012_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_1012_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_1012 *struct_RenderModel_t_1012_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1012_unwrap(winRenderModel_t_1012 *w);
typedef struct winVREvent_t_1011 winVREvent_t_1011;
extern void struct_VREvent_t_1011_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_1011_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_1011 winVRControllerState001_t_1011;
extern void struct_VRControllerState001_t_1011_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_1011_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_1011 winRenderModel_TextureMap_t_1011;
extern void struct_RenderModel_TextureMap_t_1011_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_1011_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_1011 *struct_RenderModel_TextureMap_t_1011_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1011_unwrap(winRenderModel_TextureMap_t_1011 *w);
typedef struct winRenderModel_t_1011 winRenderModel_t_1011;
extern void struct_RenderModel_t_1011_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_1011_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_1011 *struct_RenderModel_t_1011_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1011_unwrap(winRenderModel_t_1011 *w);
typedef struct winVREvent_t_1010 winVREvent_t_1010;
extern void struct_VREvent_t_1010_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_1010_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_1010 winVRControllerState001_t_1010;
extern void struct_VRControllerState001_t_1010_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_1010_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_1010 winRenderModel_TextureMap_t_1010;
extern void struct_RenderModel_TextureMap_t_1010_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_1010_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_1010 *struct_RenderModel_TextureMap_t_1010_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_1010_unwrap(winRenderModel_TextureMap_t_1010 *w);
typedef struct winRenderModel_t_1010 winRenderModel_t_1010;
extern void struct_RenderModel_t_1010_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_1010_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_1010 *struct_RenderModel_t_1010_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_1010_unwrap(winRenderModel_t_1010 *w);
typedef struct winVREvent_t_109 winVREvent_t_109;
extern void struct_VREvent_t_109_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_109_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_109 winVRControllerState001_t_109;
extern void struct_VRControllerState001_t_109_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_109_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_109 winRenderModel_TextureMap_t_109;
extern void struct_RenderModel_TextureMap_t_109_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_109_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_109 *struct_RenderModel_TextureMap_t_109_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_109_unwrap(winRenderModel_TextureMap_t_109 *w);
typedef struct winRenderModel_t_109 winRenderModel_t_109;
extern void struct_RenderModel_t_109_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_109_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_109 *struct_RenderModel_t_109_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_109_unwrap(winRenderModel_t_109 *w);
typedef struct winVREvent_t_108 winVREvent_t_108;
extern void struct_VREvent_t_108_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_108_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_108 winVRControllerState001_t_108;
extern void struct_VRControllerState001_t_108_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_108_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_108 winRenderModel_TextureMap_t_108;
extern void struct_RenderModel_TextureMap_t_108_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_108_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_108 *struct_RenderModel_TextureMap_t_108_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_108_unwrap(winRenderModel_TextureMap_t_108 *w);
typedef struct winRenderModel_t_108 winRenderModel_t_108;
extern void struct_RenderModel_t_108_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_108_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_108 *struct_RenderModel_t_108_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_108_unwrap(winRenderModel_t_108 *w);
typedef struct winVREvent_t_107 winVREvent_t_107;
extern void struct_VREvent_t_107_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_107_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_107 winVRControllerState001_t_107;
extern void struct_VRControllerState001_t_107_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_107_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_107 winRenderModel_TextureMap_t_107;
extern void struct_RenderModel_TextureMap_t_107_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_107_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_107 *struct_RenderModel_TextureMap_t_107_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_107_unwrap(winRenderModel_TextureMap_t_107 *w);
typedef struct winRenderModel_t_107 winRenderModel_t_107;
extern void struct_RenderModel_t_107_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_107_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_107 *struct_RenderModel_t_107_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_107_unwrap(winRenderModel_t_107 *w);
typedef struct winVREvent_t_106 winVREvent_t_106;
extern void struct_VREvent_t_106_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_106_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_106 winVRControllerState001_t_106;
extern void struct_VRControllerState001_t_106_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_106_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_106 winRenderModel_TextureMap_t_106;
extern void struct_RenderModel_TextureMap_t_106_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_106_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_106 *struct_RenderModel_TextureMap_t_106_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_106_unwrap(winRenderModel_TextureMap_t_106 *w);
typedef struct winRenderModel_t_106 winRenderModel_t_106;
extern void struct_RenderModel_t_106_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_106_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_106 *struct_RenderModel_t_106_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_106_unwrap(winRenderModel_t_106 *w);
typedef struct winVREvent_t_105 winVREvent_t_105;
extern void struct_VREvent_t_105_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_105_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_105 winVRControllerState001_t_105;
extern void struct_VRControllerState001_t_105_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_105_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_105 winRenderModel_TextureMap_t_105;
extern void struct_RenderModel_TextureMap_t_105_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_105_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_105 *struct_RenderModel_TextureMap_t_105_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_105_unwrap(winRenderModel_TextureMap_t_105 *w);
typedef struct winRenderModel_t_105 winRenderModel_t_105;
extern void struct_RenderModel_t_105_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_105_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_105 *struct_RenderModel_t_105_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_105_unwrap(winRenderModel_t_105 *w);
typedef struct winVREvent_t_104 winVREvent_t_104;
extern void struct_VREvent_t_104_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_104_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_104 winVRControllerState001_t_104;
extern void struct_VRControllerState001_t_104_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_104_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_104 winRenderModel_TextureMap_t_104;
extern void struct_RenderModel_TextureMap_t_104_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_104_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_104 *struct_RenderModel_TextureMap_t_104_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_104_unwrap(winRenderModel_TextureMap_t_104 *w);
typedef struct winRenderModel_t_104 winRenderModel_t_104;
extern void struct_RenderModel_t_104_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_104_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_104 *struct_RenderModel_t_104_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_104_unwrap(winRenderModel_t_104 *w);
typedef struct winVREvent_t_103a winVREvent_t_103a;
extern void struct_VREvent_t_103a_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_103a_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_103a winVRControllerState001_t_103a;
extern void struct_VRControllerState001_t_103a_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_103a_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_103a winRenderModel_TextureMap_t_103a;
extern void struct_RenderModel_TextureMap_t_103a_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_103a_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_103a *struct_RenderModel_TextureMap_t_103a_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_103a_unwrap(winRenderModel_TextureMap_t_103a *w);
typedef struct winRenderModel_t_103a winRenderModel_t_103a;
extern void struct_RenderModel_t_103a_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_103a_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_103a *struct_RenderModel_t_103a_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_103a_unwrap(winRenderModel_t_103a *w);
typedef struct winVREvent_t_103 winVREvent_t_103;
extern void struct_VREvent_t_103_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_103_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_103 winVRControllerState001_t_103;
extern void struct_VRControllerState001_t_103_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_103_win_to_lin(void *w, void *l);
typedef struct winCompositor_FrameTiming_103 winCompositor_FrameTiming_103;
extern void struct_Compositor_FrameTiming_103_lin_to_win(void *l, void *w);
extern void struct_Compositor_FrameTiming_103_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_103 winRenderModel_TextureMap_t_103;
extern void struct_RenderModel_TextureMap_t_103_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_103_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_103 *struct_RenderModel_TextureMap_t_103_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_103_unwrap(winRenderModel_TextureMap_t_103 *w);
typedef struct winRenderModel_t_103 winRenderModel_t_103;
extern void struct_RenderModel_t_103_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_103_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_103 *struct_RenderModel_t_103_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_103_unwrap(winRenderModel_t_103 *w);
typedef struct winVREvent_t_102 winVREvent_t_102;
extern void struct_VREvent_t_102_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_102_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_102 winVRControllerState001_t_102;
extern void struct_VRControllerState001_t_102_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_102_win_to_lin(void *w, void *l);
typedef struct winCompositor_FrameTiming_102 winCompositor_FrameTiming_102;
extern void struct_Compositor_FrameTiming_102_lin_to_win(void *l, void *w);
extern void struct_Compositor_FrameTiming_102_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_102 winRenderModel_TextureMap_t_102;
extern void struct_RenderModel_TextureMap_t_102_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_102_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_102 *struct_RenderModel_TextureMap_t_102_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_102_unwrap(winRenderModel_TextureMap_t_102 *w);
typedef struct winRenderModel_t_102 winRenderModel_t_102;
extern void struct_RenderModel_t_102_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_102_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_102 *struct_RenderModel_t_102_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_102_unwrap(winRenderModel_t_102 *w);
typedef struct winVREvent_t_101 winVREvent_t_101;
extern void struct_VREvent_t_101_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_101_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_101 winVRControllerState001_t_101;
extern void struct_VRControllerState001_t_101_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_101_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_101 winRenderModel_TextureMap_t_101;
extern void struct_RenderModel_TextureMap_t_101_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_101_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_101 *struct_RenderModel_TextureMap_t_101_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_101_unwrap(winRenderModel_TextureMap_t_101 *w);
typedef struct winRenderModel_t_101 winRenderModel_t_101;
extern void struct_RenderModel_t_101_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_101_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_101 *struct_RenderModel_t_101_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_101_unwrap(winRenderModel_t_101 *w);
typedef struct winVREvent_t_100 winVREvent_t_100;
extern void struct_VREvent_t_100_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_100_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_100 winVRControllerState001_t_100;
extern void struct_VRControllerState001_t_100_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_100_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_100 winRenderModel_TextureMap_t_100;
extern void struct_RenderModel_TextureMap_t_100_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_100_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_100 *struct_RenderModel_TextureMap_t_100_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_100_unwrap(winRenderModel_TextureMap_t_100 *w);
typedef struct winRenderModel_t_100 winRenderModel_t_100;
extern void struct_RenderModel_t_100_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_100_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_100 *struct_RenderModel_t_100_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_100_unwrap(winRenderModel_t_100 *w);
typedef struct winVREvent_t_0920 winVREvent_t_0920;
extern void struct_VREvent_t_0920_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_0920_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_0920 winVRControllerState001_t_0920;
extern void struct_VRControllerState001_t_0920_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_0920_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_0920 winRenderModel_TextureMap_t_0920;
extern void struct_RenderModel_TextureMap_t_0920_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_0920_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_0920 *struct_RenderModel_TextureMap_t_0920_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_0920_unwrap(winRenderModel_TextureMap_t_0920 *w);
typedef struct winRenderModel_t_0920 winRenderModel_t_0920;
extern void struct_RenderModel_t_0920_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_0920_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_0920 *struct_RenderModel_t_0920_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_0920_unwrap(winRenderModel_t_0920 *w);
typedef struct winVREvent_t_0919 winVREvent_t_0919;
extern void struct_VREvent_t_0919_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_0919_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_0919 winVRControllerState001_t_0919;
extern void struct_VRControllerState001_t_0919_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_0919_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_0919 winRenderModel_TextureMap_t_0919;
extern void struct_RenderModel_TextureMap_t_0919_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_0919_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_0919 *struct_RenderModel_TextureMap_t_0919_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_0919_unwrap(winRenderModel_TextureMap_t_0919 *w);
typedef struct winRenderModel_t_0919 winRenderModel_t_0919;
extern void struct_RenderModel_t_0919_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_0919_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_0919 *struct_RenderModel_t_0919_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_0919_unwrap(winRenderModel_t_0919 *w);
typedef struct winVREvent_t_0918 winVREvent_t_0918;
extern void struct_VREvent_t_0918_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_0918_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_0918 winVRControllerState001_t_0918;
extern void struct_VRControllerState001_t_0918_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_0918_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_0918 winRenderModel_TextureMap_t_0918;
extern void struct_RenderModel_TextureMap_t_0918_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_0918_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_0918 *struct_RenderModel_TextureMap_t_0918_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_0918_unwrap(winRenderModel_TextureMap_t_0918 *w);
typedef struct winRenderModel_t_0918 winRenderModel_t_0918;
extern void struct_RenderModel_t_0918_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_0918_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_0918 *struct_RenderModel_t_0918_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_0918_unwrap(winRenderModel_t_0918 *w);
typedef struct winVREvent_t_0917 winVREvent_t_0917;
extern void struct_VREvent_t_0917_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_0917_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_0917 winVRControllerState001_t_0917;
extern void struct_VRControllerState001_t_0917_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_0917_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_0917 winRenderModel_TextureMap_t_0917;
extern void struct_RenderModel_TextureMap_t_0917_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_0917_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_0917 *struct_RenderModel_TextureMap_t_0917_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_0917_unwrap(winRenderModel_TextureMap_t_0917 *w);
typedef struct winRenderModel_t_0917 winRenderModel_t_0917;
extern void struct_RenderModel_t_0917_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_0917_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_0917 *struct_RenderModel_t_0917_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_0917_unwrap(winRenderModel_t_0917 *w);
typedef struct winVREvent_t_0916 winVREvent_t_0916;
extern void struct_VREvent_t_0916_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_0916_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_0916 winVRControllerState001_t_0916;
extern void struct_VRControllerState001_t_0916_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_0916_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_0916 winRenderModel_TextureMap_t_0916;
extern void struct_RenderModel_TextureMap_t_0916_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_0916_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_0916 *struct_RenderModel_TextureMap_t_0916_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_0916_unwrap(winRenderModel_TextureMap_t_0916 *w);
typedef struct winRenderModel_t_0916 winRenderModel_t_0916;
extern void struct_RenderModel_t_0916_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_0916_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_0916 *struct_RenderModel_t_0916_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_0916_unwrap(winRenderModel_t_0916 *w);
typedef struct winVREvent_t_0915 winVREvent_t_0915;
extern void struct_VREvent_t_0915_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VREvent_t_0915_win_to_lin(void *w, void *l);
typedef struct winVRControllerState001_t_0915 winVRControllerState001_t_0915;
extern void struct_VRControllerState001_t_0915_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_0915_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_0915 winRenderModel_TextureMap_t_0915;
extern void struct_RenderModel_TextureMap_t_0915_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_0915_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_0915 *struct_RenderModel_TextureMap_t_0915_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_0915_unwrap(winRenderModel_TextureMap_t_0915 *w);
typedef struct winRenderModel_t_0915 winRenderModel_t_0915;
extern void struct_RenderModel_t_0915_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_0915_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_0915 *struct_RenderModel_t_0915_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_0915_unwrap(winRenderModel_t_0915 *w);
typedef struct winVRControllerState001_t_0914 winVRControllerState001_t_0914;
extern void struct_VRControllerState001_t_0914_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_0914_win_to_lin(void *w, void *l);
typedef struct winCameraVideoStreamFrame_t_0914 winCameraVideoStreamFrame_t_0914;
extern void struct_CameraVideoStreamFrame_t_0914_lin_to_win(void *l, void *w);
extern void struct_CameraVideoStreamFrame_t_0914_win_to_lin(void *w, void *l);
typedef struct winCompositor_FrameTiming_0914 winCompositor_FrameTiming_0914;
extern void struct_Compositor_FrameTiming_0914_lin_to_win(void *l, void *w);
extern void struct_Compositor_FrameTiming_0914_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_0914 winRenderModel_TextureMap_t_0914;
extern void struct_RenderModel_TextureMap_t_0914_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_0914_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_0914 *struct_RenderModel_TextureMap_t_0914_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_0914_unwrap(winRenderModel_TextureMap_t_0914 *w);
typedef struct winRenderModel_t_0914 winRenderModel_t_0914;
extern void struct_RenderModel_t_0914_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_0914_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_0914 *struct_RenderModel_t_0914_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_0914_unwrap(winRenderModel_t_0914 *w);
typedef struct winVRControllerState001_t_0913 winVRControllerState001_t_0913;
extern void struct_VRControllerState001_t_0913_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_0913_win_to_lin(void *w, void *l);
typedef struct winCameraVideoStreamFrame_t_0913 winCameraVideoStreamFrame_t_0913;
extern void struct_CameraVideoStreamFrame_t_0913_lin_to_win(void *l, void *w);
extern void struct_CameraVideoStreamFrame_t_0913_win_to_lin(void *w, void *l);
typedef struct winCompositor_FrameTiming_0913 winCompositor_FrameTiming_0913;
extern void struct_Compositor_FrameTiming_0913_lin_to_win(void *l, void *w);
extern void struct_Compositor_FrameTiming_0913_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_0913 winRenderModel_TextureMap_t_0913;
extern void struct_RenderModel_TextureMap_t_0913_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_0913_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_0913 *struct_RenderModel_TextureMap_t_0913_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_0913_unwrap(winRenderModel_TextureMap_t_0913 *w);
typedef struct winRenderModel_t_0913 winRenderModel_t_0913;
extern void struct_RenderModel_t_0913_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_0913_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_0913 *struct_RenderModel_t_0913_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_0913_unwrap(winRenderModel_t_0913 *w);
typedef struct winVRControllerState001_t_0912 winVRControllerState001_t_0912;
extern void struct_VRControllerState001_t_0912_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_0912_win_to_lin(void *w, void *l);
typedef struct winCameraVideoStreamFrame_t_0912 winCameraVideoStreamFrame_t_0912;
extern void struct_CameraVideoStreamFrame_t_0912_lin_to_win(void *l, void *w);
extern void struct_CameraVideoStreamFrame_t_0912_win_to_lin(void *w, void *l);
typedef struct winCompositor_FrameTiming_0912 winCompositor_FrameTiming_0912;
extern void struct_Compositor_FrameTiming_0912_lin_to_win(void *l, void *w);
extern void struct_Compositor_FrameTiming_0912_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_0912 winRenderModel_TextureMap_t_0912;
extern void struct_RenderModel_TextureMap_t_0912_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_0912_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_0912 *struct_RenderModel_TextureMap_t_0912_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_0912_unwrap(winRenderModel_TextureMap_t_0912 *w);
typedef struct winRenderModel_t_0912 winRenderModel_t_0912;
extern void struct_RenderModel_t_0912_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_0912_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_0912 *struct_RenderModel_t_0912_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_0912_unwrap(winRenderModel_t_0912 *w);
typedef struct winRenderModel_TextureMap_t_0910 winRenderModel_TextureMap_t_0910;
extern void struct_RenderModel_TextureMap_t_0910_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_0910_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_0910 *struct_RenderModel_TextureMap_t_0910_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_0910_unwrap(winRenderModel_TextureMap_t_0910 *w);
typedef struct winRenderModel_t_0910 winRenderModel_t_0910;
extern void struct_RenderModel_t_0910_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_0910_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_0910 *struct_RenderModel_t_0910_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_0910_unwrap(winRenderModel_t_0910 *w);
typedef struct winVRControllerState001_t_0910 winVRControllerState001_t_0910;
extern void struct_VRControllerState001_t_0910_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_0910_win_to_lin(void *w, void *l);
typedef struct winCompositor_FrameTiming_0910 winCompositor_FrameTiming_0910;
extern void struct_Compositor_FrameTiming_0910_lin_to_win(void *l, void *w);
extern void struct_Compositor_FrameTiming_0910_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_099 winRenderModel_TextureMap_t_099;
extern void struct_RenderModel_TextureMap_t_099_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_099_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_099 *struct_RenderModel_TextureMap_t_099_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_099_unwrap(winRenderModel_TextureMap_t_099 *w);
typedef struct winRenderModel_t_099 winRenderModel_t_099;
extern void struct_RenderModel_t_099_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_099_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_099 *struct_RenderModel_t_099_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_099_unwrap(winRenderModel_t_099 *w);
typedef struct winVRControllerState001_t_099 winVRControllerState001_t_099;
extern void struct_VRControllerState001_t_099_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_099_win_to_lin(void *w, void *l);
typedef struct winCompositor_FrameTiming_099 winCompositor_FrameTiming_099;
extern void struct_Compositor_FrameTiming_099_lin_to_win(void *l, void *w);
extern void struct_Compositor_FrameTiming_099_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_098 winRenderModel_TextureMap_t_098;
extern void struct_RenderModel_TextureMap_t_098_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_098_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_098 *struct_RenderModel_TextureMap_t_098_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_098_unwrap(winRenderModel_TextureMap_t_098 *w);
typedef struct winRenderModel_t_098 winRenderModel_t_098;
extern void struct_RenderModel_t_098_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_098_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_098 *struct_RenderModel_t_098_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_098_unwrap(winRenderModel_t_098 *w);
typedef struct winVRControllerState001_t_098 winVRControllerState001_t_098;
extern void struct_VRControllerState001_t_098_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_098_win_to_lin(void *w, void *l);
typedef struct winCompositor_FrameTiming_098 winCompositor_FrameTiming_098;
extern void struct_Compositor_FrameTiming_098_lin_to_win(void *l, void *w);
extern void struct_Compositor_FrameTiming_098_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_097 winRenderModel_TextureMap_t_097;
extern void struct_RenderModel_TextureMap_t_097_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_097_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_097 *struct_RenderModel_TextureMap_t_097_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_097_unwrap(winRenderModel_TextureMap_t_097 *w);
typedef struct winRenderModel_t_097 winRenderModel_t_097;
extern void struct_RenderModel_t_097_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_097_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_097 *struct_RenderModel_t_097_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_097_unwrap(winRenderModel_t_097 *w);
typedef struct winVRControllerState001_t_097 winVRControllerState001_t_097;
extern void struct_VRControllerState001_t_097_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_097_win_to_lin(void *w, void *l);
typedef struct winCompositor_FrameTiming_097 winCompositor_FrameTiming_097;
extern void struct_Compositor_FrameTiming_097_lin_to_win(void *l, void *w);
extern void struct_Compositor_FrameTiming_097_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_096 winRenderModel_TextureMap_t_096;
extern void struct_RenderModel_TextureMap_t_096_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_096_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_096 *struct_RenderModel_TextureMap_t_096_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_096_unwrap(winRenderModel_TextureMap_t_096 *w);
typedef struct winRenderModel_t_096 winRenderModel_t_096;
extern void struct_RenderModel_t_096_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_096_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_096 *struct_RenderModel_t_096_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_096_unwrap(winRenderModel_t_096 *w);
typedef struct winVRControllerState001_t_096 winVRControllerState001_t_096;
extern void struct_VRControllerState001_t_096_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_096_win_to_lin(void *w, void *l);
typedef struct winCompositor_FrameTiming_096 winCompositor_FrameTiming_096;
extern void struct_Compositor_FrameTiming_096_lin_to_win(void *l, void *w);
extern void struct_Compositor_FrameTiming_096_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_094 winRenderModel_TextureMap_t_094;
extern void struct_RenderModel_TextureMap_t_094_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_094_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_094 *struct_RenderModel_TextureMap_t_094_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_094_unwrap(winRenderModel_TextureMap_t_094 *w);
typedef struct winRenderModel_t_094 winRenderModel_t_094;
extern void struct_RenderModel_t_094_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_094_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_094 *struct_RenderModel_t_094_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_094_unwrap(winRenderModel_t_094 *w);
typedef struct winVRControllerState001_t_094 winVRControllerState001_t_094;
extern void struct_VRControllerState001_t_094_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_094_win_to_lin(void *w, void *l);
typedef struct winCompositor_FrameTiming_094 winCompositor_FrameTiming_094;
extern void struct_Compositor_FrameTiming_094_lin_to_win(void *l, void *w);
extern void struct_Compositor_FrameTiming_094_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_093 winRenderModel_TextureMap_t_093;
extern void struct_RenderModel_TextureMap_t_093_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_093_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_093 *struct_RenderModel_TextureMap_t_093_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_093_unwrap(winRenderModel_TextureMap_t_093 *w);
typedef struct winRenderModel_t_093 winRenderModel_t_093;
extern void struct_RenderModel_t_093_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_093_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_093 *struct_RenderModel_t_093_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_093_unwrap(winRenderModel_t_093 *w);
typedef struct winVRControllerState001_t_093 winVRControllerState001_t_093;
extern void struct_VRControllerState001_t_093_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_093_win_to_lin(void *w, void *l);
typedef struct winCompositor_FrameTiming_093 winCompositor_FrameTiming_093;
extern void struct_Compositor_FrameTiming_093_lin_to_win(void *l, void *w);
extern void struct_Compositor_FrameTiming_093_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_092 winRenderModel_TextureMap_t_092;
extern void struct_RenderModel_TextureMap_t_092_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_092_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_092 *struct_RenderModel_TextureMap_t_092_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_092_unwrap(winRenderModel_TextureMap_t_092 *w);
typedef struct winRenderModel_t_092 winRenderModel_t_092;
extern void struct_RenderModel_t_092_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_092_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_092 *struct_RenderModel_t_092_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_092_unwrap(winRenderModel_t_092 *w);
typedef struct winVRControllerState001_t_092 winVRControllerState001_t_092;
extern void struct_VRControllerState001_t_092_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_092_win_to_lin(void *w, void *l);
typedef struct winCompositor_FrameTiming_092 winCompositor_FrameTiming_092;
extern void struct_Compositor_FrameTiming_092_lin_to_win(void *l, void *w);
extern void struct_Compositor_FrameTiming_092_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_091 winRenderModel_TextureMap_t_091;
extern void struct_RenderModel_TextureMap_t_091_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_091_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_091 *struct_RenderModel_TextureMap_t_091_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_091_unwrap(winRenderModel_TextureMap_t_091 *w);
typedef struct winRenderModel_t_091 winRenderModel_t_091;
extern void struct_RenderModel_t_091_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_091_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_091 *struct_RenderModel_t_091_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_091_unwrap(winRenderModel_t_091 *w);
typedef struct winVRControllerState001_t_091 winVRControllerState001_t_091;
extern void struct_VRControllerState001_t_091_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_091_win_to_lin(void *w, void *l);
typedef struct winCompositor_FrameTiming_091 winCompositor_FrameTiming_091;
extern void struct_Compositor_FrameTiming_091_lin_to_win(void *l, void *w);
extern void struct_Compositor_FrameTiming_091_win_to_lin(void *w, void *l);
typedef struct winRenderModel_TextureMap_t_090 winRenderModel_TextureMap_t_090;
extern void struct_RenderModel_TextureMap_t_090_lin_to_win(void *l, void *w);
extern void struct_RenderModel_TextureMap_t_090_win_to_lin(void *w, void *l);
extern struct winRenderModel_TextureMap_t_090 *struct_RenderModel_TextureMap_t_090_wrap(void *l);
extern RenderModel_TextureMap_t *struct_RenderModel_TextureMap_t_090_unwrap(winRenderModel_TextureMap_t_090 *w);
typedef struct winRenderModel_t_090 winRenderModel_t_090;
extern void struct_RenderModel_t_090_lin_to_win(void *l, void *w);
extern void struct_RenderModel_t_090_win_to_lin(void *w, void *l);
extern struct winRenderModel_t_090 *struct_RenderModel_t_090_wrap(void *l);
extern RenderModel_t *struct_RenderModel_t_090_unwrap(winRenderModel_t_090 *w);
typedef struct winVRControllerState001_t_090 winVRControllerState001_t_090;
extern void struct_VRControllerState001_t_090_lin_to_win(void *l, void *w, uint32_t sz);
extern void struct_VRControllerState001_t_090_win_to_lin(void *w, void *l);
typedef struct winCompositor_FrameTiming_090 winCompositor_FrameTiming_090;
extern void struct_Compositor_FrameTiming_090_lin_to_win(void *l, void *w);
extern void struct_Compositor_FrameTiming_090_win_to_lin(void *w, void *l);
