name: Compatibility Report
description: Suggest Game compatibility issues.
title: '[Compatibility] '
labels: compatibility

body:
  - type: markdown
    attributes:
      value: |
        ## Please fill out forms as cleanly as possible.
         1. You can find the Steam AppID in the URL of the shop page of the game. e.g. for `The Witcher 3: Wild Hunt` the AppID is `292030`.
         2. You can find your driver and Linux version, as well as your graphics processor's name in the system information report of Steam.
         3. You can retrieve a full system information report by clicking `Help` then `System Information` in the Steam client on your machine.
         4. Please copy it to your clipboard by pressing `Ctrl+A` and then `Ctrl+C`. Then paste it in a [Gist](https://gist.github.com/) and post the link in this issue.
         5. Please search for open issues and pull requests by the name of the game and find out whether they are relevant and should be referenced above.
        #### Make sure that you have
        * properly edited & filled in the title of this bug report
  - type: dropdown
    id: version
    attributes:
      label: Proton Version
      description: |
        What Proton version are you using?
      multiple: false
      options:
        - Proton-Experimental
        - Proton-6.3-x
        - Proton-5.13-x
        - Proton-5.0-x
        - Proton-4.11-x
        - Proton-4.2-x
        - Proton-3.16-x
        - Proton-3.7-x
        - Git
        - Other
    validations:
      required: true
  - type: dropdown
    id: OS
    attributes:
      label: What Operating System are you using?
      multiple: false
      options:
        - SteamOS
        - Debian
        - Ubuntu
        - Arch
        - Linux x86
        - Linux x86_64
        - Linux ARM (Raspberry Pi)
        - Other
    validations:
      required: false
  - type: input
    id: other
    attributes:
      label: If Other OS, please describe
      description: Other details
      placeholder: "SteamOS, Debian 11, Ubuntu 20.04, Arch, etc."
    validations:
      required: false
  - type: textarea
    id: appid
    attributes:
      label: Compatibility Report
      description: |
         Name of the game with compatibility issues:
         Steam AppID of the game
      placeholder: "https://store.steampowered.com/app/70/HalfLife/"
    validations:
      required: true
  - type: textarea
    id: system
    attributes:
      label: System Information
      description: |
         GPU: 'e.g. RX 580 or GTX 970'
         Driver/LLVM version: 'e.g. Mesa 18.2/7.0.0 or nvidia 396.54'
         Kernel version: 'e.g. 4.17'
         Link to full system information report as [Gist](https://gist.github.com/):
         Proton version:
      placeholder: "Provide some basic system information"
    validations:
      required: false
  - type: checkboxes
    id: checked
    attributes:
      label: I confirm
      description: I have searched and not found similar issues.
      options:
        - label: I haven't found an existing compatibility report for this game.
          required: true
        - label: I have checked whether there are updates for my system available.
          required: true
  - type: textarea
    id: log
    attributes:
      label: Provide a Log
      description: Please avoid pasting the full log, _use attachments or links_ in a [Gist](https://gist.github.com/)
      placeholder: "Please add PROTON_LOG=1 %command% to the game's launch options and attach the generated $HOME/steam-$APPID.log to this issue report as a file. (Proton logs compress well if needed.)"
    validations:
      required: false
  - type: textarea
    id: issues
    attributes:
      label: "Symptoms What's the problem?"
      description: Describe any problems with the gameplay
      placeholder: "Describe symptoms or issues"
    validations:
      required: false
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce the behaviour.
      description: How can we reproduce this?
      value: |
        Explain how to reproduce
        1. 
        2.
        3.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Add any other context or screenshots about the compatibility report here.
      description: Screenshots or Links?
      placeholder: "Ex. Screenshot or Link"
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct & Contributing Guidelines
      description: By submitting this issue, you agree to follow our [contributing guidelines](https://docs.github.com/articles/github-community-guidelines) and code of conduct.
      options:
        - label: Yes, I agree.
          required: true
  - type: markdown
    attributes:
      value: |
         * Make sure you have properly filled in the title of this bug report
