FontName                   (SourceHanSansSC-Bold)
FullName                   (Source Han Sans Simplified Chinese Bold)
FamilyName                 (Source Han Sans Simplified Chinese)
Weight                     (Bold)
version                    (2.005)
Registry                   (Adobe)
Ordering                   (Identity)
Supplement                 0
Layout                     (AI0-SourceHanSans)
FSType                     0
isFixedPitch               false
UnderlinePosition          -150
AdobeCopyright             (Copyright 2014-2025 Adobe (http://www.adobe.com/), with Reserved Font Name 'Source'.)
Trademark                  (Source is a trademark of Adobe in the United States and/or other countries.)
Serif                      false
IsBoldStyle                true
IsItalicStyle              false
PreferOS/2TypoMetrics      false
IsOS/2WidthWeigthSlopeOnly false
IsOS/2OBLIQUE              false
UseOldNameID4              false
LicenseCode                ADOBE
