extern EGameSearchErrorCode_t cppISteamGameSearch_SteamMatchGameSearch001_AddGameSearchParams(void *, const char *, const char *);
extern EGameSearchErrorCode_t cppISteamGameSearch_SteamMatchGameSearch001_SearchForGameWithLobby(void *, CSteamID, int, int);
extern EGameSearchErrorCode_t cppISteamGameSearch_SteamMatchGameSearch001_SearchForGameSolo(void *, int, int);
extern EGameSearchErrorCode_t cppISteamGameSearch_SteamMatchGameSearch001_AcceptGame(void *);
extern EGameSearchErrorCode_t cppISteamGameSearch_SteamMatchGameSearch001_DeclineGame(void *);
extern EGameSearchErrorCode_t cppISteamGameSearch_SteamMatchGameSearch001_RetrieveConnectionDetails(void *, CSteamID, char *, int);
extern EGameSearchErrorCode_t cppISteamGameSearch_SteamMatchGameSearch001_EndGameSearch(void *);
extern EGameSearchErrorCode_t cppISteamGameSearch_SteamMatchGameSearch001_SetGameHostParams(void *, const char *, const char *);
extern EGameSearchErrorCode_t cppISteamGameSearch_SteamMatchGameSearch001_SetConnectionDetails(void *, const char *, int);
extern EGameSearchErrorCode_t cppISteamGameSearch_SteamMatchGameSearch001_RequestPlayersForGame(void *, int, int, int);
extern EGameSearchErrorCode_t cppISteamGameSearch_SteamMatchGameSearch001_HostConfirmGameStart(void *, uint64);
extern EGameSearchErrorCode_t cppISteamGameSearch_SteamMatchGameSearch001_CancelRequestPlayersForGame(void *);
extern EGameSearchErrorCode_t cppISteamGameSearch_SteamMatchGameSearch001_SubmitPlayerResult(void *, uint64, CSteamID, EPlayerResult_t);
extern EGameSearchErrorCode_t cppISteamGameSearch_SteamMatchGameSearch001_EndGame(void *, uint64);
