extern HSteamUser cppISteamUser_SteamUser023_GetHSteamUser(void *);
extern bool cppISteamUser_SteamUser023_BLoggedOn(void *);
extern CSteamID cppISteamUser_SteamUser023_GetSteamID(void *);
extern int cppISteamUser_SteamUser023_InitiateGameConnection_DEPRECATED(void *, void *, int, CSteamID, uint32, uint16, bool);
extern void cppISteamUser_SteamUser023_TerminateGameConnection_DEPRECATED(void *, uint32, uint16);
extern void cppISteamUser_SteamUser023_TrackAppUsageEvent(void *, CGameID, int, const char *);
extern bool cppISteamUser_SteamUser023_GetUserDataFolder(void *, char *, int);
extern void cppISteamUser_SteamUser023_StartVoiceRecording(void *);
extern void cppISteamUser_SteamUser023_StopVoiceRecording(void *);
extern EVoiceResult cppISteamUser_SteamUser023_GetAvailableVoice(void *, uint32 *, uint32 *, uint32);
extern EVoiceResult cppISteamUser_SteamUser023_GetVoice(void *, bool, void *, uint32, uint32 *, bool, void *, uint32, uint32 *, uint32);
extern EVoiceResult cppISteamUser_SteamUser023_DecompressVoice(void *, const void *, uint32, void *, uint32, uint32 *, uint32);
extern uint32 cppISteamUser_SteamUser023_GetVoiceOptimalSampleRate(void *);
extern HAuthTicket cppISteamUser_SteamUser023_GetAuthSessionTicket(void *, void *, int, uint32 *, const SteamNetworkingIdentity *);
extern HAuthTicket cppISteamUser_SteamUser023_GetAuthTicketForWebApi(void *, const char *);
extern EBeginAuthSessionResult cppISteamUser_SteamUser023_BeginAuthSession(void *, const void *, int, CSteamID);
extern void cppISteamUser_SteamUser023_EndAuthSession(void *, CSteamID);
extern void cppISteamUser_SteamUser023_CancelAuthTicket(void *, HAuthTicket);
extern EUserHasLicenseForAppResult cppISteamUser_SteamUser023_UserHasLicenseForApp(void *, CSteamID, AppId_t);
extern bool cppISteamUser_SteamUser023_BIsBehindNAT(void *);
extern void cppISteamUser_SteamUser023_AdvertiseGame(void *, CSteamID, uint32, uint16);
extern SteamAPICall_t cppISteamUser_SteamUser023_RequestEncryptedAppTicket(void *, void *, int);
extern bool cppISteamUser_SteamUser023_GetEncryptedAppTicket(void *, void *, int, uint32 *);
extern int cppISteamUser_SteamUser023_GetGameBadgeLevel(void *, int, bool);
extern int cppISteamUser_SteamUser023_GetPlayerSteamLevel(void *);
extern SteamAPICall_t cppISteamUser_SteamUser023_RequestStoreAuthURL(void *, const char *);
extern bool cppISteamUser_SteamUser023_BIsPhoneVerified(void *);
extern bool cppISteamUser_SteamUser023_BIsTwoFactorEnabled(void *);
extern bool cppISteamUser_SteamUser023_BIsPhoneIdentifying(void *);
extern bool cppISteamUser_SteamUser023_BIsPhoneRequiringVerification(void *);
extern SteamAPICall_t cppISteamUser_SteamUser023_GetMarketEligibility(void *);
extern SteamAPICall_t cppISteamUser_SteamUser023_GetDurationControl(void *);
extern bool cppISteamUser_SteamUser023_BSetDurationControlOnlineState(void *, EDurationControlOnlineState);
