extern HSteamUser cppISteamUser_SteamUser021_GetHSteamUser(void *);
extern bool cppISteamUser_SteamUser021_BLoggedOn(void *);
extern CSteamID cppISteamUser_SteamUser021_GetSteamID(void *);
extern int cppISteamUser_SteamUser021_InitiateGameConnection(void *, void *, int, CSteamID, uint32, uint16, bool);
extern void cppISteamUser_SteamUser021_TerminateGameConnection(void *, uint32, uint16);
extern void cppISteamUser_SteamUser021_TrackAppUsageEvent(void *, CGameID, int, const char *);
extern bool cppISteamUser_SteamUser021_GetUserDataFolder(void *, char *, int);
extern void cppISteamUser_SteamUser021_StartVoiceRecording(void *);
extern void cppISteamUser_SteamUser021_StopVoiceRecording(void *);
extern EVoiceResult cppISteamUser_SteamUser021_GetAvailableVoice(void *, uint32 *, uint32 *, uint32);
extern EVoiceResult cppISteamUser_SteamUser021_GetVoice(void *, bool, void *, uint32, uint32 *, bool, void *, uint32, uint32 *, uint32);
extern EVoiceResult cppISteamUser_SteamUser021_DecompressVoice(void *, const void *, uint32, void *, uint32, uint32 *, uint32);
extern uint32 cppISteamUser_SteamUser021_GetVoiceOptimalSampleRate(void *);
extern HAuthTicket cppISteamUser_SteamUser021_GetAuthSessionTicket(void *, void *, int, uint32 *);
extern EBeginAuthSessionResult cppISteamUser_SteamUser021_BeginAuthSession(void *, const void *, int, CSteamID);
extern void cppISteamUser_SteamUser021_EndAuthSession(void *, CSteamID);
extern void cppISteamUser_SteamUser021_CancelAuthTicket(void *, HAuthTicket);
extern EUserHasLicenseForAppResult cppISteamUser_SteamUser021_UserHasLicenseForApp(void *, CSteamID, AppId_t);
extern bool cppISteamUser_SteamUser021_BIsBehindNAT(void *);
extern void cppISteamUser_SteamUser021_AdvertiseGame(void *, CSteamID, uint32, uint16);
extern SteamAPICall_t cppISteamUser_SteamUser021_RequestEncryptedAppTicket(void *, void *, int);
extern bool cppISteamUser_SteamUser021_GetEncryptedAppTicket(void *, void *, int, uint32 *);
extern int cppISteamUser_SteamUser021_GetGameBadgeLevel(void *, int, bool);
extern int cppISteamUser_SteamUser021_GetPlayerSteamLevel(void *);
extern SteamAPICall_t cppISteamUser_SteamUser021_RequestStoreAuthURL(void *, const char *);
extern bool cppISteamUser_SteamUser021_BIsPhoneVerified(void *);
extern bool cppISteamUser_SteamUser021_BIsTwoFactorEnabled(void *);
extern bool cppISteamUser_SteamUser021_BIsPhoneIdentifying(void *);
extern bool cppISteamUser_SteamUser021_BIsPhoneRequiringVerification(void *);
extern SteamAPICall_t cppISteamUser_SteamUser021_GetMarketEligibility(void *);
extern SteamAPICall_t cppISteamUser_SteamUser021_GetDurationControl(void *);
