extern bool cppISteamGameServer_SteamGameServer015_InitGameServer(void *, uint32, uint16, uint16, uint32, AppId_t, const char *);
extern void cppISteamGameServer_SteamGameServer015_SetProduct(void *, const char *);
extern void cppISteamGameServer_SteamGameServer015_SetGameDescription(void *, const char *);
extern void cppISteamGameServer_SteamGameServer015_SetModDir(void *, const char *);
extern void cppISteamGameServer_SteamGameServer015_SetDedicatedServer(void *, bool);
extern void cppISteamGameServer_SteamGameServer015_LogOn(void *, const char *);
extern void cppISteamGameServer_SteamGameServer015_LogOnAnonymous(void *);
extern void cppISteamGameServer_SteamGameServer015_LogOff(void *);
extern bool cppISteamGameServer_SteamGameServer015_BLoggedOn(void *);
extern bool cppISteamGameServer_SteamGameServer015_BSecure(void *);
extern CSteamID cppISteamGameServer_SteamGameServer015_GetSteamID(void *);
extern bool cppISteamGameServer_SteamGameServer015_WasRestartRequested(void *);
extern void cppISteamGameServer_SteamGameServer015_SetMaxPlayerCount(void *, int);
extern void cppISteamGameServer_SteamGameServer015_SetBotPlayerCount(void *, int);
extern void cppISteamGameServer_SteamGameServer015_SetServerName(void *, const char *);
extern void cppISteamGameServer_SteamGameServer015_SetMapName(void *, const char *);
extern void cppISteamGameServer_SteamGameServer015_SetPasswordProtected(void *, bool);
extern void cppISteamGameServer_SteamGameServer015_SetSpectatorPort(void *, uint16);
extern void cppISteamGameServer_SteamGameServer015_SetSpectatorServerName(void *, const char *);
extern void cppISteamGameServer_SteamGameServer015_ClearAllKeyValues(void *);
extern void cppISteamGameServer_SteamGameServer015_SetKeyValue(void *, const char *, const char *);
extern void cppISteamGameServer_SteamGameServer015_SetGameTags(void *, const char *);
extern void cppISteamGameServer_SteamGameServer015_SetGameData(void *, const char *);
extern void cppISteamGameServer_SteamGameServer015_SetRegion(void *, const char *);
extern void cppISteamGameServer_SteamGameServer015_SetAdvertiseServerActive(void *, bool);
extern HAuthTicket cppISteamGameServer_SteamGameServer015_GetAuthSessionTicket(void *, void *, int, uint32 *, const SteamNetworkingIdentity *);
extern EBeginAuthSessionResult cppISteamGameServer_SteamGameServer015_BeginAuthSession(void *, const void *, int, CSteamID);
extern void cppISteamGameServer_SteamGameServer015_EndAuthSession(void *, CSteamID);
extern void cppISteamGameServer_SteamGameServer015_CancelAuthTicket(void *, HAuthTicket);
extern EUserHasLicenseForAppResult cppISteamGameServer_SteamGameServer015_UserHasLicenseForApp(void *, CSteamID, AppId_t);
extern bool cppISteamGameServer_SteamGameServer015_RequestUserGroupStatus(void *, CSteamID, CSteamID);
extern void cppISteamGameServer_SteamGameServer015_GetGameplayStats(void *);
extern SteamAPICall_t cppISteamGameServer_SteamGameServer015_GetServerReputation(void *);
extern SteamIPAddress_t cppISteamGameServer_SteamGameServer015_GetPublicIP(void *);
extern bool cppISteamGameServer_SteamGameServer015_HandleIncomingPacket(void *, const void *, int, uint32, uint16);
extern int cppISteamGameServer_SteamGameServer015_GetNextOutgoingPacket(void *, void *, int, uint32 *, uint16 *);
extern SteamAPICall_t cppISteamGameServer_SteamGameServer015_AssociateWithClan(void *, CSteamID);
extern SteamAPICall_t cppISteamGameServer_SteamGameServer015_ComputeNewPlayerCompatibility(void *, CSteamID);
extern bool cppISteamGameServer_SteamGameServer015_SendUserConnectAndAuthenticate_DEPRECATED(void *, uint32, const void *, uint32, CSteamID *);
extern CSteamID cppISteamGameServer_SteamGameServer015_CreateUnauthenticatedUserConnection(void *);
extern void cppISteamGameServer_SteamGameServer015_SendUserDisconnect_DEPRECATED(void *, CSteamID);
extern bool cppISteamGameServer_SteamGameServer015_BUpdateUserData(void *, CSteamID, const char *, uint32);
extern void cppISteamGameServer_SteamGameServer015_SetMasterServerHeartbeatInterval_DEPRECATED(void *, int);
extern void cppISteamGameServer_SteamGameServer015_ForceMasterServerHeartbeat_DEPRECATED(void *);
