extern ESteamNetworkingAvailability cppISteamNetworkingUtils_SteamNetworkingUtils002_GetRelayNetworkStatus(void *, SteamRelayNetworkStatus_t *);
extern float cppISteamNetworkingUtils_SteamNetworkingUtils002_GetLocalPingLocation(void *, SteamNetworkPingLocation_t *);
extern int cppISteamNetworkingUtils_SteamNetworkingUtils002_EstimatePingTimeBetweenTwoLocations(void *, const SteamNetworkPingLocation_t *, const SteamNetworkPingLocation_t *);
extern int cppISteamNetworkingUtils_SteamNetworkingUtils002_EstimatePingTimeFromLocalHost(void *, const SteamNetworkPingLocation_t *);
extern void cppISteamNetworkingUtils_SteamNetworkingUtils002_ConvertPingLocationToString(void *, const SteamNetworkPingLocation_t *, char *, int);
extern bool cppISteamNetworkingUtils_SteamNetworkingUtils002_ParsePingLocationString(void *, const char *, SteamNetworkPingLocation_t *);
extern bool cppISteamNetworkingUtils_SteamNetworkingUtils002_CheckPingDataUpToDate(void *, float);
extern int cppISteamNetworkingUtils_SteamNetworkingUtils002_GetPingToDataCenter(void *, SteamNetworkingPOPID, SteamNetworkingPOPID *);
extern int cppISteamNetworkingUtils_SteamNetworkingUtils002_GetDirectPingToPOP(void *, SteamNetworkingPOPID);
extern int cppISteamNetworkingUtils_SteamNetworkingUtils002_GetPOPCount(void *);
extern int cppISteamNetworkingUtils_SteamNetworkingUtils002_GetPOPList(void *, SteamNetworkingPOPID *, int);
extern SteamNetworkingMicroseconds cppISteamNetworkingUtils_SteamNetworkingUtils002_GetLocalTimestamp(void *);
extern void cppISteamNetworkingUtils_SteamNetworkingUtils002_SetDebugOutputFunction(void *, ESteamNetworkingSocketsDebugOutputType, FSteamNetworkingSocketsDebugOutput);
extern bool cppISteamNetworkingUtils_SteamNetworkingUtils002_SetConfigValue(void *, ESteamNetworkingConfigValue, ESteamNetworkingConfigScope, intptr_t, ESteamNetworkingConfigDataType, const void *);
extern ESteamNetworkingGetConfigValueResult cppISteamNetworkingUtils_SteamNetworkingUtils002_GetConfigValue(void *, ESteamNetworkingConfigValue, ESteamNetworkingConfigScope, intptr_t, ESteamNetworkingConfigDataType *, void *, size_t *);
extern bool cppISteamNetworkingUtils_SteamNetworkingUtils002_GetConfigValueInfo(void *, ESteamNetworkingConfigValue, const char **, ESteamNetworkingConfigDataType *, ESteamNetworkingConfigScope *, ESteamNetworkingConfigValue *);
extern ESteamNetworkingConfigValue cppISteamNetworkingUtils_SteamNetworkingUtils002_GetFirstConfigValue(void *);
extern void cppISteamNetworkingUtils_SteamNetworkingUtils002_SteamNetworkingIPAddr_ToString(void *, const SteamNetworkingIPAddr *, char *, size_t, bool);
extern bool cppISteamNetworkingUtils_SteamNetworkingUtils002_SteamNetworkingIPAddr_ParseString(void *, SteamNetworkingIPAddr *, const char *);
extern void cppISteamNetworkingUtils_SteamNetworkingUtils002_SteamNetworkingIdentity_ToString(void *, const SteamNetworkingIdentity *, char *, size_t);
extern bool cppISteamNetworkingUtils_SteamNetworkingUtils002_SteamNetworkingIdentity_ParseString(void *, SteamNetworkingIdentity *, const char *);
