extern const char * cppISteamFriends_SteamFriends014_GetPersonaName(void *);
extern SteamAPICall_t cppISteamFriends_SteamFriends014_SetPersonaName(void *, const char *);
extern EPersonaState cppISteamFriends_SteamFriends014_GetPersonaState(void *);
extern int cppISteamFriends_SteamFriends014_GetFriendCount(void *, int);
extern CSteamID cppISteamFriends_SteamFriends014_GetFriendByIndex(void *, int, int);
extern EFriendRelationship cppISteamFriends_SteamFriends014_GetFriendRelationship(void *, CSteamID);
extern EPersonaState cppISteamFriends_SteamFriends014_GetFriendPersonaState(void *, CSteamID);
extern const char * cppISteamFriends_SteamFriends014_GetFriendPersonaName(void *, CSteamID);
extern bool cppISteamFriends_SteamFriends014_GetFriendGamePlayed(void *, CSteamID, FriendGameInfo_t *);
extern const char * cppISteamFriends_SteamFriends014_GetFriendPersonaNameHistory(void *, CSteamID, int);
extern const char * cppISteamFriends_SteamFriends014_GetPlayerNickname(void *, CSteamID);
extern bool cppISteamFriends_SteamFriends014_HasFriend(void *, CSteamID, int);
extern int cppISteamFriends_SteamFriends014_GetClanCount(void *);
extern CSteamID cppISteamFriends_SteamFriends014_GetClanByIndex(void *, int);
extern const char * cppISteamFriends_SteamFriends014_GetClanName(void *, CSteamID);
extern const char * cppISteamFriends_SteamFriends014_GetClanTag(void *, CSteamID);
extern bool cppISteamFriends_SteamFriends014_GetClanActivityCounts(void *, CSteamID, int *, int *, int *);
extern SteamAPICall_t cppISteamFriends_SteamFriends014_DownloadClanActivityCounts(void *, CSteamID *, int);
extern int cppISteamFriends_SteamFriends014_GetFriendCountFromSource(void *, CSteamID);
extern CSteamID cppISteamFriends_SteamFriends014_GetFriendFromSourceByIndex(void *, CSteamID, int);
extern bool cppISteamFriends_SteamFriends014_IsUserInSource(void *, CSteamID, CSteamID);
extern void cppISteamFriends_SteamFriends014_SetInGameVoiceSpeaking(void *, CSteamID, bool);
extern void cppISteamFriends_SteamFriends014_ActivateGameOverlay(void *, const char *);
extern void cppISteamFriends_SteamFriends014_ActivateGameOverlayToUser(void *, const char *, CSteamID);
extern void cppISteamFriends_SteamFriends014_ActivateGameOverlayToWebPage(void *, const char *);
extern void cppISteamFriends_SteamFriends014_ActivateGameOverlayToStore(void *, AppId_t, EOverlayToStoreFlag);
extern void cppISteamFriends_SteamFriends014_SetPlayedWith(void *, CSteamID);
extern void cppISteamFriends_SteamFriends014_ActivateGameOverlayInviteDialog(void *, CSteamID);
extern int cppISteamFriends_SteamFriends014_GetSmallFriendAvatar(void *, CSteamID);
extern int cppISteamFriends_SteamFriends014_GetMediumFriendAvatar(void *, CSteamID);
extern int cppISteamFriends_SteamFriends014_GetLargeFriendAvatar(void *, CSteamID);
extern bool cppISteamFriends_SteamFriends014_RequestUserInformation(void *, CSteamID, bool);
extern SteamAPICall_t cppISteamFriends_SteamFriends014_RequestClanOfficerList(void *, CSteamID);
extern CSteamID cppISteamFriends_SteamFriends014_GetClanOwner(void *, CSteamID);
extern int cppISteamFriends_SteamFriends014_GetClanOfficerCount(void *, CSteamID);
extern CSteamID cppISteamFriends_SteamFriends014_GetClanOfficerByIndex(void *, CSteamID, int);
extern uint32 cppISteamFriends_SteamFriends014_GetUserRestrictions(void *);
extern bool cppISteamFriends_SteamFriends014_SetRichPresence(void *, const char *, const char *);
extern void cppISteamFriends_SteamFriends014_ClearRichPresence(void *);
extern const char * cppISteamFriends_SteamFriends014_GetFriendRichPresence(void *, CSteamID, const char *);
extern int cppISteamFriends_SteamFriends014_GetFriendRichPresenceKeyCount(void *, CSteamID);
extern const char * cppISteamFriends_SteamFriends014_GetFriendRichPresenceKeyByIndex(void *, CSteamID, int);
extern void cppISteamFriends_SteamFriends014_RequestFriendRichPresence(void *, CSteamID);
extern bool cppISteamFriends_SteamFriends014_InviteUserToGame(void *, CSteamID, const char *);
extern int cppISteamFriends_SteamFriends014_GetCoplayFriendCount(void *);
extern CSteamID cppISteamFriends_SteamFriends014_GetCoplayFriend(void *, int);
extern int cppISteamFriends_SteamFriends014_GetFriendCoplayTime(void *, CSteamID);
extern AppId_t cppISteamFriends_SteamFriends014_GetFriendCoplayGame(void *, CSteamID);
extern SteamAPICall_t cppISteamFriends_SteamFriends014_JoinClanChatRoom(void *, CSteamID);
extern bool cppISteamFriends_SteamFriends014_LeaveClanChatRoom(void *, CSteamID);
extern int cppISteamFriends_SteamFriends014_GetClanChatMemberCount(void *, CSteamID);
extern CSteamID cppISteamFriends_SteamFriends014_GetChatMemberByIndex(void *, CSteamID, int);
extern bool cppISteamFriends_SteamFriends014_SendClanChatMessage(void *, CSteamID, const char *);
extern int cppISteamFriends_SteamFriends014_GetClanChatMessage(void *, CSteamID, int, void *, int, EChatEntryType *, CSteamID *);
extern bool cppISteamFriends_SteamFriends014_IsClanChatAdmin(void *, CSteamID, CSteamID);
extern bool cppISteamFriends_SteamFriends014_IsClanChatWindowOpenInSteam(void *, CSteamID);
extern bool cppISteamFriends_SteamFriends014_OpenClanChatWindowInSteam(void *, CSteamID);
extern bool cppISteamFriends_SteamFriends014_CloseClanChatWindowInSteam(void *, CSteamID);
extern bool cppISteamFriends_SteamFriends014_SetListenForFriendsMessages(void *, bool);
extern bool cppISteamFriends_SteamFriends014_ReplyToFriendMessage(void *, CSteamID, const char *);
extern int cppISteamFriends_SteamFriends014_GetFriendMessage(void *, CSteamID, int, void *, int, EChatEntryType *);
extern SteamAPICall_t cppISteamFriends_SteamFriends014_GetFollowerCount(void *, CSteamID);
extern SteamAPICall_t cppISteamFriends_SteamFriends014_IsFollowing(void *, CSteamID);
extern SteamAPICall_t cppISteamFriends_SteamFriends014_EnumerateFollowingList(void *, uint32);
