extern uint32 cppISteamUtils_SteamUtils010_GetSecondsSinceAppActive(void *);
extern uint32 cppISteamUtils_SteamUtils010_GetSecondsSinceComputerActive(void *);
extern EUniverse cppISteamUtils_SteamUtils010_GetConnectedUniverse(void *);
extern uint32 cppISteamUtils_SteamUtils010_GetServerRealTime(void *);
extern const char * cppISteamUtils_SteamUtils010_GetIPCountry(void *);
extern bool cppISteamUtils_SteamUtils010_GetImageSize(void *, int, uint32 *, uint32 *);
extern bool cppISteamUtils_SteamUtils010_GetImageRGBA(void *, int, uint8 *, int);
extern bool cppISteamUtils_SteamUtils010_GetCSERIPPort(void *, uint32 *, uint16 *);
extern uint8 cppISteamUtils_SteamUtils010_GetCurrentBatteryPower(void *);
extern uint32 cppISteamUtils_SteamUtils010_GetAppID(void *);
extern void cppISteamUtils_SteamUtils010_SetOverlayNotificationPosition(void *, ENotificationPosition);
extern bool cppISteamUtils_SteamUtils010_IsAPICallCompleted(void *, SteamAPICall_t, bool *);
extern ESteamAPICallFailure cppISteamUtils_SteamUtils010_GetAPICallFailureReason(void *, SteamAPICall_t);
extern bool cppISteamUtils_SteamUtils010_GetAPICallResult(void *, SteamAPICall_t, void *, int, int, bool *);
extern void cppISteamUtils_SteamUtils010_RunFrame(void *);
extern uint32 cppISteamUtils_SteamUtils010_GetIPCCallCount(void *);
extern void cppISteamUtils_SteamUtils010_SetWarningMessageHook(void *, SteamAPIWarningMessageHook_t);
extern bool cppISteamUtils_SteamUtils010_IsOverlayEnabled(void *);
extern bool cppISteamUtils_SteamUtils010_BOverlayNeedsPresent(void *);
extern SteamAPICall_t cppISteamUtils_SteamUtils010_CheckFileSignature(void *, const char *);
extern bool cppISteamUtils_SteamUtils010_ShowGamepadTextInput(void *, EGamepadTextInputMode, EGamepadTextInputLineMode, const char *, uint32, const char *);
extern uint32 cppISteamUtils_SteamUtils010_GetEnteredGamepadTextLength(void *);
extern bool cppISteamUtils_SteamUtils010_GetEnteredGamepadTextInput(void *, char *, uint32);
extern const char * cppISteamUtils_SteamUtils010_GetSteamUILanguage(void *);
extern bool cppISteamUtils_SteamUtils010_IsSteamRunningInVR(void *);
extern void cppISteamUtils_SteamUtils010_SetOverlayNotificationInset(void *, int, int);
extern bool cppISteamUtils_SteamUtils010_IsSteamInBigPictureMode(void *);
extern void cppISteamUtils_SteamUtils010_StartVRDashboard(void *);
extern bool cppISteamUtils_SteamUtils010_IsVRHeadsetStreamingEnabled(void *);
extern void cppISteamUtils_SteamUtils010_SetVRHeadsetStreamingEnabled(void *, bool);
extern bool cppISteamUtils_SteamUtils010_IsSteamChinaLauncher(void *);
extern bool cppISteamUtils_SteamUtils010_InitFilterText(void *, uint32);
extern int cppISteamUtils_SteamUtils010_FilterText(void *, ETextFilteringContext, CSteamID, const char *, char *, uint32);
extern ESteamIPv6ConnectivityState cppISteamUtils_SteamUtils010_GetIPv6ConnectivityState(void *, ESteamIPv6ConnectivityProtocol);
extern bool cppISteamUtils_SteamUtils010_IsSteamRunningOnSteamDeck(void *);
extern bool cppISteamUtils_SteamUtils010_ShowFloatingGamepadTextInput(void *, EFloatingGamepadTextInputMode, int, int, int, int);
extern void cppISteamUtils_SteamUtils010_SetGameLauncherMode(void *, bool);
extern bool cppISteamUtils_SteamUtils010_DismissFloatingGamepadTextInput(void *);
