extern bool cppISteamController_SteamController008_Init(void *);
extern bool cppISteamController_SteamController008_Shutdown(void *);
extern void cppISteamController_SteamController008_RunFrame(void *);
extern int cppISteamController_SteamController008_GetConnectedControllers(void *, ControllerHandle_t *);
extern ControllerActionSetHandle_t cppISteamController_SteamController008_GetActionSetHandle(void *, const char *);
extern void cppISteamController_SteamController008_ActivateActionSet(void *, ControllerHandle_t, ControllerActionSetHandle_t);
extern ControllerActionSetHandle_t cppISteamController_SteamController008_GetCurrentActionSet(void *, ControllerHandle_t);
extern void cppISteamController_SteamController008_ActivateActionSetLayer(void *, ControllerHandle_t, ControllerActionSetHandle_t);
extern void cppISteamController_SteamController008_DeactivateActionSetLayer(void *, ControllerHandle_t, ControllerActionSetHandle_t);
extern void cppISteamController_SteamController008_DeactivateAllActionSetLayers(void *, ControllerHandle_t);
extern int cppISteamController_SteamController008_GetActiveActionSetLayers(void *, ControllerHandle_t, ControllerActionSetHandle_t *);
extern ControllerDigitalActionHandle_t cppISteamController_SteamController008_GetDigitalActionHandle(void *, const char *);
extern InputDigitalActionData_t cppISteamController_SteamController008_GetDigitalActionData(void *, ControllerHandle_t, ControllerDigitalActionHandle_t);
extern int cppISteamController_SteamController008_GetDigitalActionOrigins(void *, ControllerHandle_t, ControllerActionSetHandle_t, ControllerDigitalActionHandle_t, EControllerActionOrigin *);
extern ControllerAnalogActionHandle_t cppISteamController_SteamController008_GetAnalogActionHandle(void *, const char *);
extern InputAnalogActionData_t cppISteamController_SteamController008_GetAnalogActionData(void *, ControllerHandle_t, ControllerAnalogActionHandle_t);
extern int cppISteamController_SteamController008_GetAnalogActionOrigins(void *, ControllerHandle_t, ControllerActionSetHandle_t, ControllerAnalogActionHandle_t, EControllerActionOrigin *);
extern const char * cppISteamController_SteamController008_GetGlyphForActionOrigin(void *, EControllerActionOrigin);
extern const char * cppISteamController_SteamController008_GetStringForActionOrigin(void *, EControllerActionOrigin);
extern void cppISteamController_SteamController008_StopAnalogActionMomentum(void *, ControllerHandle_t, ControllerAnalogActionHandle_t);
extern InputMotionData_t cppISteamController_SteamController008_GetMotionData(void *, ControllerHandle_t);
extern void cppISteamController_SteamController008_TriggerHapticPulse(void *, ControllerHandle_t, ESteamControllerPad, unsigned short);
extern void cppISteamController_SteamController008_TriggerRepeatedHapticPulse(void *, ControllerHandle_t, ESteamControllerPad, unsigned short, unsigned short, unsigned short, unsigned int);
extern void cppISteamController_SteamController008_TriggerVibration(void *, ControllerHandle_t, unsigned short, unsigned short);
extern void cppISteamController_SteamController008_SetLEDColor(void *, ControllerHandle_t, uint8, uint8, uint8, unsigned int);
extern bool cppISteamController_SteamController008_ShowBindingPanel(void *, ControllerHandle_t);
extern ESteamInputType cppISteamController_SteamController008_GetInputTypeForHandle(void *, ControllerHandle_t);
extern ControllerHandle_t cppISteamController_SteamController008_GetControllerForGamepadIndex(void *, int);
extern int cppISteamController_SteamController008_GetGamepadIndexForController(void *, ControllerHandle_t);
extern const char * cppISteamController_SteamController008_GetStringForXboxOrigin(void *, EXboxOrigin);
extern const char * cppISteamController_SteamController008_GetGlyphForXboxOrigin(void *, EXboxOrigin);
extern EControllerActionOrigin cppISteamController_SteamController008_GetActionOriginFromXboxOrigin(void *, ControllerHandle_t, EXboxOrigin);
extern EControllerActionOrigin cppISteamController_SteamController008_TranslateActionOrigin(void *, ESteamInputType, EControllerActionOrigin);
extern bool cppISteamController_SteamController008_GetControllerBindingRevision(void *, ControllerHandle_t, int *, int *);
