extern bool cppISteamInput_SteamInput002_Init(void *);
extern bool cppISteamInput_SteamInput002_Shutdown(void *);
extern void cppISteamInput_SteamInput002_RunFrame(void *);
extern int cppISteamInput_SteamInput002_GetConnectedControllers(void *, InputHandle_t *);
extern InputActionSetHandle_t cppISteamInput_SteamInput002_GetActionSetHandle(void *, const char *);
extern void cppISteamInput_SteamInput002_ActivateActionSet(void *, InputHandle_t, InputActionSetHandle_t);
extern InputActionSetHandle_t cppISteamInput_SteamInput002_GetCurrentActionSet(void *, InputHandle_t);
extern void cppISteamInput_SteamInput002_ActivateActionSetLayer(void *, InputHandle_t, InputActionSetHandle_t);
extern void cppISteamInput_SteamInput002_DeactivateActionSetLayer(void *, InputHandle_t, InputActionSetHandle_t);
extern void cppISteamInput_SteamInput002_DeactivateAllActionSetLayers(void *, InputHandle_t);
extern int cppISteamInput_SteamInput002_GetActiveActionSetLayers(void *, InputHandle_t, InputActionSetHandle_t *);
extern InputDigitalActionHandle_t cppISteamInput_SteamInput002_GetDigitalActionHandle(void *, const char *);
extern InputDigitalActionData_t cppISteamInput_SteamInput002_GetDigitalActionData(void *, InputHandle_t, InputDigitalActionHandle_t);
extern int cppISteamInput_SteamInput002_GetDigitalActionOrigins(void *, InputHandle_t, InputActionSetHandle_t, InputDigitalActionHandle_t, EInputActionOrigin *);
extern InputAnalogActionHandle_t cppISteamInput_SteamInput002_GetAnalogActionHandle(void *, const char *);
extern InputAnalogActionData_t cppISteamInput_SteamInput002_GetAnalogActionData(void *, InputHandle_t, InputAnalogActionHandle_t);
extern int cppISteamInput_SteamInput002_GetAnalogActionOrigins(void *, InputHandle_t, InputActionSetHandle_t, InputAnalogActionHandle_t, EInputActionOrigin *);
extern const char * cppISteamInput_SteamInput002_GetGlyphForActionOrigin(void *, EInputActionOrigin);
extern const char * cppISteamInput_SteamInput002_GetStringForActionOrigin(void *, EInputActionOrigin);
extern void cppISteamInput_SteamInput002_StopAnalogActionMomentum(void *, InputHandle_t, InputAnalogActionHandle_t);
extern InputMotionData_t cppISteamInput_SteamInput002_GetMotionData(void *, InputHandle_t);
extern void cppISteamInput_SteamInput002_TriggerVibration(void *, InputHandle_t, unsigned short, unsigned short);
extern void cppISteamInput_SteamInput002_SetLEDColor(void *, InputHandle_t, uint8, uint8, uint8, unsigned int);
extern void cppISteamInput_SteamInput002_TriggerHapticPulse(void *, InputHandle_t, ESteamControllerPad, unsigned short);
extern void cppISteamInput_SteamInput002_TriggerRepeatedHapticPulse(void *, InputHandle_t, ESteamControllerPad, unsigned short, unsigned short, unsigned short, unsigned int);
extern bool cppISteamInput_SteamInput002_ShowBindingPanel(void *, InputHandle_t);
extern ESteamInputType cppISteamInput_SteamInput002_GetInputTypeForHandle(void *, InputHandle_t);
extern InputHandle_t cppISteamInput_SteamInput002_GetControllerForGamepadIndex(void *, int);
extern int cppISteamInput_SteamInput002_GetGamepadIndexForController(void *, InputHandle_t);
extern const char * cppISteamInput_SteamInput002_GetStringForXboxOrigin(void *, EXboxOrigin);
extern const char * cppISteamInput_SteamInput002_GetGlyphForXboxOrigin(void *, EXboxOrigin);
extern EInputActionOrigin cppISteamInput_SteamInput002_GetActionOriginFromXboxOrigin(void *, InputHandle_t, EXboxOrigin);
extern EInputActionOrigin cppISteamInput_SteamInput002_TranslateActionOrigin(void *, ESteamInputType, EInputActionOrigin);
extern bool cppISteamInput_SteamInput002_GetDeviceBindingRevision(void *, InputHandle_t, int *, int *);
extern uint32 cppISteamInput_SteamInput002_GetRemotePlaySessionID(void *, InputHandle_t);
