/* Automatically generated from OpenXR xr.xml; DO NOT EDIT!
 *
 * This file is generated from OpenXR xr.xml file covered
 * by the following copyright and permission notice:
 *
 * Copyright (c) 2017-2026 The Khronos Group Inc.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 * ------------------------------------------------------------------------
 *
 * This file, xr.xml, is the OpenXR API Registry. It is a critically important
 * and normative part of the OpenXR Specification, including a canonical
 * machine-readable definition of the API, parameter and member validation
 * language incorporated into the Specification and reference pages, and other
 * material which is registered by Khronos, such as tags used by extension and
 * layer authors. The only authoritative version of xr.xml is the one
 * maintained in the default branch of the Khronos OpenXR GitHub project.
 *
 */

#ifndef __WINE_OPENXR_THUNKS_H
#define __WINE_OPENXR_THUNKS_H

#define WINE_XR_VERSION XR_API_VERSION_1_1

/* Functions for which we have custom implementations outside of the thunks. */
XrResult wine_xrConvertTimeToWin32PerformanceCounterKHR(XrInstance instance, XrTime time, LARGE_INTEGER *performanceCounter);
XrResult wine_xrConvertWin32PerformanceCounterToTimeKHR(XrInstance instance, const LARGE_INTEGER *performanceCounter, XrTime *time);
XrResult wine_xrCreateInstance(const XrInstanceCreateInfo *createInfo, XrInstance *instance);
XrResult wine_xrCreateSession(XrInstance instance, const XrSessionCreateInfo *createInfo, XrSession *session);
XrResult wine_xrCreateSwapchain(XrSession session, const XrSwapchainCreateInfo *createInfo, XrSwapchain *swapchain);
XrResult wine_xrDestroySession(XrSession session);
XrResult wine_xrEnumerateInstanceExtensionProperties(const char *layerName, uint32_t propertyCapacityInput, uint32_t *propertyCountOutput, XrExtensionProperties *properties);
XrResult wine_xrGetVulkanGraphicsDevice2KHR(XrInstance instance, const XrVulkanGraphicsDeviceGetInfoKHR *getInfo, VkPhysicalDevice *vulkanPhysicalDevice);
XrResult wine_xrGetVulkanGraphicsDeviceKHR(XrInstance instance, XrSystemId systemId, VkInstance vkInstance, VkPhysicalDevice *vkPhysicalDevice);
XrResult wine_xrGetVulkanInstanceExtensionsKHR(XrInstance instance, XrSystemId systemId, uint32_t bufferCapacityInput, uint32_t *bufferCountOutput, char *buffer);

#define ALL_XR_INSTANCE_FUNCS() \
    USE_XR_FUNC(xrAcquireSwapchainImage) \
    USE_XR_FUNC(xrAddTrackableImageDatabaseANDROID) \
    USE_XR_FUNC(xrAllocateWorldMeshBufferML) \
    USE_XR_FUNC(xrApplyForceFeedbackCurlMNDX) \
    USE_XR_FUNC(xrApplyHapticFeedback) \
    USE_XR_FUNC(xrAttachSessionActionSets) \
    USE_XR_FUNC(xrBeginFrame) \
    USE_XR_FUNC(xrBeginPlaneDetectionEXT) \
    USE_XR_FUNC(xrBeginSession) \
    USE_XR_FUNC(xrBeginSpatialContainerRenderingEXT) \
    USE_XR_FUNC(xrCancelFutureEXT) \
    USE_XR_FUNC(xrCaptureSceneAsyncBD) \
    USE_XR_FUNC(xrCaptureSceneCompleteBD) \
    USE_XR_FUNC(xrChangeVirtualKeyboardTextContextMETA) \
    USE_XR_FUNC(xrCheckVpsAvailabilityAsyncANDROID) \
    USE_XR_FUNC(xrCheckVpsAvailabilityCompleteANDROID) \
    USE_XR_FUNC(xrClearSpatialAnchorStoreMSFT) \
    USE_XR_FUNC(xrComputeNewSceneMSFT) \
    USE_XR_FUNC(xrConvertTimeToWin32PerformanceCounterKHR) \
    USE_XR_FUNC(xrConvertWin32PerformanceCounterToTimeKHR) \
    USE_XR_FUNC(xrCreateAction) \
    USE_XR_FUNC(xrCreateActionSet) \
    USE_XR_FUNC(xrCreateActionSpace) \
    USE_XR_FUNC(xrCreateAnchorSpaceANDROID) \
    USE_XR_FUNC(xrCreateAnchorSpaceBD) \
    USE_XR_FUNC(xrCreateApiLayerInstance) \
    USE_XR_FUNC(xrCreateBodyTrackerBD) \
    USE_XR_FUNC(xrCreateBodyTrackerFB) \
    USE_XR_FUNC(xrCreateBodyTrackerHTC) \
    USE_XR_FUNC(xrCreateDeviceAnchorPersistenceANDROID) \
    USE_XR_FUNC(xrCreateExportedLocalizationMapML) \
    USE_XR_FUNC(xrCreateEyeTrackerANDROID) \
    USE_XR_FUNC(xrCreateEyeTrackerFB) \
    USE_XR_FUNC(xrCreateFaceTracker2FB) \
    USE_XR_FUNC(xrCreateFaceTrackerANDROID) \
    USE_XR_FUNC(xrCreateFaceTrackerBD) \
    USE_XR_FUNC(xrCreateFaceTrackerFB) \
    USE_XR_FUNC(xrCreateFacialExpressionClientML) \
    USE_XR_FUNC(xrCreateFacialTrackerHTC) \
    USE_XR_FUNC(xrCreateFoveationProfileFB) \
    USE_XR_FUNC(xrCreateGeometryInstanceFB) \
    USE_XR_FUNC(xrCreateGeospatialAnchorANDROID) \
    USE_XR_FUNC(xrCreateGeospatialTrackerANDROID) \
    USE_XR_FUNC(xrCreateHandMeshSpaceMSFT) \
    USE_XR_FUNC(xrCreateHandTrackerEXT) \
    USE_XR_FUNC(xrCreateKeyboardSpaceFB) \
    USE_XR_FUNC(xrCreateLightEstimatorANDROID) \
    USE_XR_FUNC(xrCreateMarkerDetectorML) \
    USE_XR_FUNC(xrCreateMarkerSpaceML) \
    USE_XR_FUNC(xrCreateMarkerSpaceVARJO) \
    USE_XR_FUNC(xrCreatePassthroughColorLutMETA) \
    USE_XR_FUNC(xrCreatePassthroughFB) \
    USE_XR_FUNC(xrCreatePassthroughHTC) \
    USE_XR_FUNC(xrCreatePassthroughLayerANDROID) \
    USE_XR_FUNC(xrCreatePassthroughLayerFB) \
    USE_XR_FUNC(xrCreatePersistedAnchorSpaceANDROID) \
    USE_XR_FUNC(xrCreatePlaneDetectorEXT) \
    USE_XR_FUNC(xrCreateReferenceSpace) \
    USE_XR_FUNC(xrCreateRenderModelAssetEXT) \
    USE_XR_FUNC(xrCreateRenderModelEXT) \
    USE_XR_FUNC(xrCreateRenderModelSpaceEXT) \
    USE_XR_FUNC(xrCreateSceneMSFT) \
    USE_XR_FUNC(xrCreateSceneMeshSnapshotANDROID) \
    USE_XR_FUNC(xrCreateSceneMeshingTrackerANDROID) \
    USE_XR_FUNC(xrCreateSceneObserverMSFT) \
    USE_XR_FUNC(xrCreateSenseDataProviderBD) \
    USE_XR_FUNC(xrCreateSession) \
    USE_XR_FUNC(xrCreateSoundFieldBD) \
    USE_XR_FUNC(xrCreateSoundObjectBD) \
    USE_XR_FUNC(xrCreateSoundObstacleBD) \
    USE_XR_FUNC(xrCreateSoundObstacleMaterialBD) \
    USE_XR_FUNC(xrCreateSpaceUserFB) \
    USE_XR_FUNC(xrCreateSpatialAnchorAsyncBD) \
    USE_XR_FUNC(xrCreateSpatialAnchorCompleteBD) \
    USE_XR_FUNC(xrCreateSpatialAnchorEXT) \
    USE_XR_FUNC(xrCreateSpatialAnchorFB) \
    USE_XR_FUNC(xrCreateSpatialAnchorFromPersistedNameMSFT) \
    USE_XR_FUNC(xrCreateSpatialAnchorHTC) \
    USE_XR_FUNC(xrCreateSpatialAnchorMSFT) \
    USE_XR_FUNC(xrCreateSpatialAnchorSpaceANDROID) \
    USE_XR_FUNC(xrCreateSpatialAnchorSpaceFromIdANDROID) \
    USE_XR_FUNC(xrCreateSpatialAnchorSpaceMSFT) \
    USE_XR_FUNC(xrCreateSpatialAnchorStoreConnectionMSFT) \
    USE_XR_FUNC(xrCreateSpatialAnchorsAsyncML) \
    USE_XR_FUNC(xrCreateSpatialAnchorsCompleteML) \
    USE_XR_FUNC(xrCreateSpatialAnchorsStorageML) \
    USE_XR_FUNC(xrCreateSpatialAudioRendererBD) \
    USE_XR_FUNC(xrCreateSpatialContainerEXT) \
    USE_XR_FUNC(xrCreateSpatialContainerSpaceEXT) \
    USE_XR_FUNC(xrCreateSpatialContextAsyncEXT) \
    USE_XR_FUNC(xrCreateSpatialContextCompleteEXT) \
    USE_XR_FUNC(xrCreateSpatialDiscoverySnapshotAsyncEXT) \
    USE_XR_FUNC(xrCreateSpatialDiscoverySnapshotCompleteEXT) \
    USE_XR_FUNC(xrCreateSpatialEntityAnchorBD) \
    USE_XR_FUNC(xrCreateSpatialEntityFromIdEXT) \
    USE_XR_FUNC(xrCreateSpatialGraphNodeSpaceMSFT) \
    USE_XR_FUNC(xrCreateSpatialImageTrackingDatabaseAsyncEXT) \
    USE_XR_FUNC(xrCreateSpatialImageTrackingDatabaseCompleteEXT) \
    USE_XR_FUNC(xrCreateSpatialPersistenceContextAsyncEXT) \
    USE_XR_FUNC(xrCreateSpatialPersistenceContextCompleteEXT) \
    USE_XR_FUNC(xrCreateSpatialRaycastSnapshotANDROID) \
    USE_XR_FUNC(xrCreateSpatialUpdateSnapshotEXT) \
    USE_XR_FUNC(xrCreateSurfaceAnchorAsyncANDROID) \
    USE_XR_FUNC(xrCreateSurfaceAnchorCompleteANDROID) \
    USE_XR_FUNC(xrCreateSwapchain) \
    USE_XR_FUNC(xrCreateTrackableImageDatabaseAsyncANDROID) \
    USE_XR_FUNC(xrCreateTrackableImageDatabaseCompleteANDROID) \
    USE_XR_FUNC(xrCreateTrackableTrackerANDROID) \
    USE_XR_FUNC(xrCreateVirtualKeyboardMETA) \
    USE_XR_FUNC(xrCreateVirtualKeyboardSpaceMETA) \
    USE_XR_FUNC(xrCreateVulkanDeviceKHR) \
    USE_XR_FUNC(xrCreateVulkanInstanceKHR) \
    USE_XR_FUNC(xrCreateWorldMeshDetectorML) \
    USE_XR_FUNC(xrDeleteSpatialAnchorsAsyncML) \
    USE_XR_FUNC(xrDeleteSpatialAnchorsCompleteML) \
    USE_XR_FUNC(xrDeserializeSceneMSFT) \
    USE_XR_FUNC(xrDestroyAction) \
    USE_XR_FUNC(xrDestroyActionSet) \
    USE_XR_FUNC(xrDestroyAnchorBD) \
    USE_XR_FUNC(xrDestroyBodyTrackerBD) \
    USE_XR_FUNC(xrDestroyBodyTrackerFB) \
    USE_XR_FUNC(xrDestroyBodyTrackerHTC) \
    USE_XR_FUNC(xrDestroyDeviceAnchorPersistenceANDROID) \
    USE_XR_FUNC(xrDestroyExportedLocalizationMapML) \
    USE_XR_FUNC(xrDestroyEyeTrackerANDROID) \
    USE_XR_FUNC(xrDestroyEyeTrackerFB) \
    USE_XR_FUNC(xrDestroyFaceTracker2FB) \
    USE_XR_FUNC(xrDestroyFaceTrackerANDROID) \
    USE_XR_FUNC(xrDestroyFaceTrackerBD) \
    USE_XR_FUNC(xrDestroyFaceTrackerFB) \
    USE_XR_FUNC(xrDestroyFacialExpressionClientML) \
    USE_XR_FUNC(xrDestroyFacialTrackerHTC) \
    USE_XR_FUNC(xrDestroyFoveationProfileFB) \
    USE_XR_FUNC(xrDestroyGeometryInstanceFB) \
    USE_XR_FUNC(xrDestroyGeospatialTrackerANDROID) \
    USE_XR_FUNC(xrDestroyHandTrackerEXT) \
    USE_XR_FUNC(xrDestroyInstance) \
    USE_XR_FUNC(xrDestroyLightEstimatorANDROID) \
    USE_XR_FUNC(xrDestroyMarkerDetectorML) \
    USE_XR_FUNC(xrDestroyPassthroughColorLutMETA) \
    USE_XR_FUNC(xrDestroyPassthroughFB) \
    USE_XR_FUNC(xrDestroyPassthroughHTC) \
    USE_XR_FUNC(xrDestroyPassthroughLayerANDROID) \
    USE_XR_FUNC(xrDestroyPassthroughLayerFB) \
    USE_XR_FUNC(xrDestroyPlaneDetectorEXT) \
    USE_XR_FUNC(xrDestroyRenderModelAssetEXT) \
    USE_XR_FUNC(xrDestroyRenderModelEXT) \
    USE_XR_FUNC(xrDestroySceneMSFT) \
    USE_XR_FUNC(xrDestroySceneMeshSnapshotANDROID) \
    USE_XR_FUNC(xrDestroySceneMeshingTrackerANDROID) \
    USE_XR_FUNC(xrDestroySceneObserverMSFT) \
    USE_XR_FUNC(xrDestroySenseDataProviderBD) \
    USE_XR_FUNC(xrDestroySenseDataSnapshotBD) \
    USE_XR_FUNC(xrDestroySession) \
    USE_XR_FUNC(xrDestroySoundFieldBD) \
    USE_XR_FUNC(xrDestroySoundObjectBD) \
    USE_XR_FUNC(xrDestroySoundObstacleBD) \
    USE_XR_FUNC(xrDestroySoundObstacleMaterialBD) \
    USE_XR_FUNC(xrDestroySpace) \
    USE_XR_FUNC(xrDestroySpaceUserFB) \
    USE_XR_FUNC(xrDestroySpatialAnchorMSFT) \
    USE_XR_FUNC(xrDestroySpatialAnchorStoreConnectionMSFT) \
    USE_XR_FUNC(xrDestroySpatialAnchorsStorageML) \
    USE_XR_FUNC(xrDestroySpatialAudioRendererBD) \
    USE_XR_FUNC(xrDestroySpatialContainerEXT) \
    USE_XR_FUNC(xrDestroySpatialContextEXT) \
    USE_XR_FUNC(xrDestroySpatialEntityEXT) \
    USE_XR_FUNC(xrDestroySpatialGraphNodeBindingMSFT) \
    USE_XR_FUNC(xrDestroySpatialImageTrackingDatabaseEXT) \
    USE_XR_FUNC(xrDestroySpatialPersistenceContextEXT) \
    USE_XR_FUNC(xrDestroySpatialSnapshotEXT) \
    USE_XR_FUNC(xrDestroySwapchain) \
    USE_XR_FUNC(xrDestroyTrackableImageDatabaseANDROID) \
    USE_XR_FUNC(xrDestroyTrackableTrackerANDROID) \
    USE_XR_FUNC(xrDestroyVirtualKeyboardMETA) \
    USE_XR_FUNC(xrDestroyWorldMeshDetectorML) \
    USE_XR_FUNC(xrDownloadSharedSpatialAnchorAsyncBD) \
    USE_XR_FUNC(xrDownloadSharedSpatialAnchorCompleteBD) \
    USE_XR_FUNC(xrEnableLocalizationEventsML) \
    USE_XR_FUNC(xrEnableUserCalibrationEventsML) \
    USE_XR_FUNC(xrEndAudioPeriodBD) \
    USE_XR_FUNC(xrEndFrame) \
    USE_XR_FUNC(xrEndSession) \
    USE_XR_FUNC(xrEndSpatialContainerRenderingEXT) \
    USE_XR_FUNC(xrEnumerateApiLayerProperties) \
    USE_XR_FUNC(xrEnumerateBoundSourcesForAction) \
    USE_XR_FUNC(xrEnumerateColorSpacesFB) \
    USE_XR_FUNC(xrEnumerateColorSpacesSONY) \
    USE_XR_FUNC(xrEnumerateDisplayRefreshRatesFB) \
    USE_XR_FUNC(xrEnumerateEnvironmentBlendModes) \
    USE_XR_FUNC(xrEnumerateEnvironmentTexturePixelFormatsBD) \
    USE_XR_FUNC(xrEnumerateEnvironmentTextureResolutionsBD) \
    USE_XR_FUNC(xrEnumerateEnvironmentTextureTransferTypesBD) \
    USE_XR_FUNC(xrEnumerateExternalCamerasOCULUS) \
    USE_XR_FUNC(xrEnumerateFacialSimulationModesBD) \
    USE_XR_FUNC(xrEnumerateInstanceExtensionProperties) \
    USE_XR_FUNC(xrEnumerateInteractionRenderModelIdsEXT) \
    USE_XR_FUNC(xrEnumeratePerformanceMetricsCounterPathsANDROID) \
    USE_XR_FUNC(xrEnumeratePerformanceMetricsCounterPathsMETA) \
    USE_XR_FUNC(xrEnumeratePersistedAnchorsANDROID) \
    USE_XR_FUNC(xrEnumeratePersistedSpatialAnchorNamesMSFT) \
    USE_XR_FUNC(xrEnumerateRaycastSupportedTrackableTypesANDROID) \
    USE_XR_FUNC(xrEnumerateReferenceSpaces) \
    USE_XR_FUNC(xrEnumerateRenderModelPathsFB) \
    USE_XR_FUNC(xrEnumerateRenderModelSubactionPathsEXT) \
    USE_XR_FUNC(xrEnumerateReprojectionModesMSFT) \
    USE_XR_FUNC(xrEnumerateSceneComputeFeaturesMSFT) \
    USE_XR_FUNC(xrEnumerateSpaceSupportedComponentsFB) \
    USE_XR_FUNC(xrEnumerateSpatialAnchorAttachableComponentsANDROID) \
    USE_XR_FUNC(xrEnumerateSpatialCapabilitiesEXT) \
    USE_XR_FUNC(xrEnumerateSpatialCapabilityComponentTypesEXT) \
    USE_XR_FUNC(xrEnumerateSpatialCapabilityFeaturesEXT) \
    USE_XR_FUNC(xrEnumerateSpatialEntityComponentTypesBD) \
    USE_XR_FUNC(xrEnumerateSpatialPersistenceScopesEXT) \
    USE_XR_FUNC(xrEnumerateSpatialReferenceImageFormatsEXT) \
    USE_XR_FUNC(xrEnumerateSupportedAnchorTrackableTypesANDROID) \
    USE_XR_FUNC(xrEnumerateSupportedAudioSampleRateBD) \
    USE_XR_FUNC(xrEnumerateSupportedPersistenceAnchorTypesANDROID) \
    USE_XR_FUNC(xrEnumerateSupportedSemanticLabelSetsANDROID) \
    USE_XR_FUNC(xrEnumerateSupportedSpatialContainerGraphicsPresentationsEXT) \
    USE_XR_FUNC(xrEnumerateSupportedTrackableTypesANDROID) \
    USE_XR_FUNC(xrEnumerateSwapchainFormats) \
    USE_XR_FUNC(xrEnumerateSwapchainImages) \
    USE_XR_FUNC(xrEnumerateViewConfigurationViews) \
    USE_XR_FUNC(xrEnumerateViewConfigurations) \
    USE_XR_FUNC(xrEnumerateViveTrackerPathsHTCX) \
    USE_XR_FUNC(xrEraseSpaceFB) \
    USE_XR_FUNC(xrEraseSpacesMETA) \
    USE_XR_FUNC(xrFreeWorldMeshBufferML) \
    USE_XR_FUNC(xrGeometryInstanceSetTransformFB) \
    USE_XR_FUNC(xrGetActionStateBoolean) \
    USE_XR_FUNC(xrGetActionStateFloat) \
    USE_XR_FUNC(xrGetActionStatePose) \
    USE_XR_FUNC(xrGetActionStateVector2f) \
    USE_XR_FUNC(xrGetAllSubmeshStatesANDROID) \
    USE_XR_FUNC(xrGetAllTrackablesANDROID) \
    USE_XR_FUNC(xrGetAnchorPersistStateANDROID) \
    USE_XR_FUNC(xrGetAnchorUuidBD) \
    USE_XR_FUNC(xrGetAudioInputDeviceGuidOculus) \
    USE_XR_FUNC(xrGetAudioOutputDeviceGuidOculus) \
    USE_XR_FUNC(xrGetBodySkeletonFB) \
    USE_XR_FUNC(xrGetBodySkeletonHTC) \
    USE_XR_FUNC(xrGetBodyTrackingStateBD) \
    USE_XR_FUNC(xrGetCoarseTrackingEyesInfoANDROID) \
    USE_XR_FUNC(xrGetControllerModelKeyMSFT) \
    USE_XR_FUNC(xrGetControllerModelPropertiesMSFT) \
    USE_XR_FUNC(xrGetControllerModelStateMSFT) \
    USE_XR_FUNC(xrGetCurrentInteractionProfile) \
    USE_XR_FUNC(xrGetD3D11GraphicsRequirementsKHR) \
    USE_XR_FUNC(xrGetD3D12GraphicsRequirementsKHR) \
    USE_XR_FUNC(xrGetDeviceSampleRateFB) \
    USE_XR_FUNC(xrGetDisplayRefreshRateFB) \
    USE_XR_FUNC(xrGetExportedLocalizationMapDataML) \
    USE_XR_FUNC(xrGetEyeGazesFB) \
    USE_XR_FUNC(xrGetFaceCalibrationStateANDROID) \
    USE_XR_FUNC(xrGetFaceExpressionWeights2FB) \
    USE_XR_FUNC(xrGetFaceExpressionWeightsFB) \
    USE_XR_FUNC(xrGetFaceStateANDROID) \
    USE_XR_FUNC(xrGetFacialExpressionBlendShapePropertiesML) \
    USE_XR_FUNC(xrGetFacialExpressionsHTC) \
    USE_XR_FUNC(xrGetFacialSimulationDataBD) \
    USE_XR_FUNC(xrGetFacialSimulationModeBD) \
    USE_XR_FUNC(xrGetFineTrackingEyesInfoANDROID) \
    USE_XR_FUNC(xrGetFoveationEyeTrackedStateMETA) \
    USE_XR_FUNC(xrGetHandGestureQCOM) \
    USE_XR_FUNC(xrGetHandMeshFB) \
    USE_XR_FUNC(xrGetInputSourceLocalizedName) \
    USE_XR_FUNC(xrGetInstanceProperties) \
    USE_XR_FUNC(xrGetLightEstimateANDROID) \
    USE_XR_FUNC(xrGetMarkerDetectorStateML) \
    USE_XR_FUNC(xrGetMarkerLengthML) \
    USE_XR_FUNC(xrGetMarkerNumberML) \
    USE_XR_FUNC(xrGetMarkerReprojectionErrorML) \
    USE_XR_FUNC(xrGetMarkerSizeVARJO) \
    USE_XR_FUNC(xrGetMarkerStringML) \
    USE_XR_FUNC(xrGetMarkersML) \
    USE_XR_FUNC(xrGetOpenGLGraphicsRequirementsKHR) \
    USE_XR_FUNC(xrGetPassthroughCameraStateANDROID) \
    USE_XR_FUNC(xrGetPassthroughPreferencesMETA) \
    USE_XR_FUNC(xrGetPerformanceMetricsStateANDROID) \
    USE_XR_FUNC(xrGetPerformanceMetricsStateMETA) \
    USE_XR_FUNC(xrGetPlaneDetectionStateEXT) \
    USE_XR_FUNC(xrGetPlaneDetectionsEXT) \
    USE_XR_FUNC(xrGetPlanePolygonBufferEXT) \
    USE_XR_FUNC(xrGetQueriedSenseDataBD) \
    USE_XR_FUNC(xrGetRecommendedLayerResolutionMETA) \
    USE_XR_FUNC(xrGetReferenceSpaceBoundsRect) \
    USE_XR_FUNC(xrGetRenderModelAssetDataEXT) \
    USE_XR_FUNC(xrGetRenderModelAssetPropertiesEXT) \
    USE_XR_FUNC(xrGetRenderModelPoseTopLevelUserPathEXT) \
    USE_XR_FUNC(xrGetRenderModelPropertiesEXT) \
    USE_XR_FUNC(xrGetRenderModelPropertiesFB) \
    USE_XR_FUNC(xrGetRenderModelStateEXT) \
    USE_XR_FUNC(xrGetSceneComponentsMSFT) \
    USE_XR_FUNC(xrGetSceneComputeStateMSFT) \
    USE_XR_FUNC(xrGetSceneMarkerDecodedStringMSFT) \
    USE_XR_FUNC(xrGetSceneMarkerRawDataMSFT) \
    USE_XR_FUNC(xrGetSceneMeshBuffersMSFT) \
    USE_XR_FUNC(xrGetSenseDataProviderStateBD) \
    USE_XR_FUNC(xrGetSerializedSceneFragmentDataMSFT) \
    USE_XR_FUNC(xrGetSpaceBoundary2DFB) \
    USE_XR_FUNC(xrGetSpaceBoundingBox2DFB) \
    USE_XR_FUNC(xrGetSpaceBoundingBox3DFB) \
    USE_XR_FUNC(xrGetSpaceComponentStatusFB) \
    USE_XR_FUNC(xrGetSpaceContainerFB) \
    USE_XR_FUNC(xrGetSpaceRoomLayoutFB) \
    USE_XR_FUNC(xrGetSpaceRoomMeshFaceIndicesMETA) \
    USE_XR_FUNC(xrGetSpaceRoomMeshMETA) \
    USE_XR_FUNC(xrGetSpaceSemanticLabelsFB) \
    USE_XR_FUNC(xrGetSpaceTriangleMeshMETA) \
    USE_XR_FUNC(xrGetSpaceUserIdFB) \
    USE_XR_FUNC(xrGetSpaceUuidFB) \
    USE_XR_FUNC(xrGetSpatialAnchorNameHTC) \
    USE_XR_FUNC(xrGetSpatialAnchorStateML) \
    USE_XR_FUNC(xrGetSpatialBufferFloatEXT) \
    USE_XR_FUNC(xrGetSpatialBufferStringEXT) \
    USE_XR_FUNC(xrGetSpatialBufferUint16EXT) \
    USE_XR_FUNC(xrGetSpatialBufferUint32EXT) \
    USE_XR_FUNC(xrGetSpatialBufferUint8EXT) \
    USE_XR_FUNC(xrGetSpatialBufferVector2fEXT) \
    USE_XR_FUNC(xrGetSpatialBufferVector3fEXT) \
    USE_XR_FUNC(xrGetSpatialContainerBoundsEXT) \
    USE_XR_FUNC(xrGetSpatialContainerStateEXT) \
    USE_XR_FUNC(xrGetSpatialEntityComponentDataBD) \
    USE_XR_FUNC(xrGetSpatialEntityUuidBD) \
    USE_XR_FUNC(xrGetSpatialGraphNodeBindingPropertiesMSFT) \
    USE_XR_FUNC(xrGetStationaryReferenceSpaceGenerationIdEXT) \
    USE_XR_FUNC(xrGetSubmeshDataANDROID) \
    USE_XR_FUNC(xrGetSwapchainStateFB) \
    USE_XR_FUNC(xrGetSystem) \
    USE_XR_FUNC(xrGetSystemProperties) \
    USE_XR_FUNC(xrGetTrackableImageANDROID) \
    USE_XR_FUNC(xrGetTrackableMarkerANDROID) \
    USE_XR_FUNC(xrGetTrackableObjectANDROID) \
    USE_XR_FUNC(xrGetTrackablePlaneANDROID) \
    USE_XR_FUNC(xrGetTrackableQrCodeANDROID) \
    USE_XR_FUNC(xrGetViewConfigurationProperties) \
    USE_XR_FUNC(xrGetVirtualKeyboardDirtyTexturesMETA) \
    USE_XR_FUNC(xrGetVirtualKeyboardModelAnimationStatesMETA) \
    USE_XR_FUNC(xrGetVirtualKeyboardScaleMETA) \
    USE_XR_FUNC(xrGetVirtualKeyboardTextureDataMETA) \
    USE_XR_FUNC(xrGetVisibilityMaskKHR) \
    USE_XR_FUNC(xrGetVulkanDeviceExtensionsKHR) \
    USE_XR_FUNC(xrGetVulkanGraphicsDevice2KHR) \
    USE_XR_FUNC(xrGetVulkanGraphicsDeviceKHR) \
    USE_XR_FUNC(xrGetVulkanGraphicsRequirements2KHR) \
    USE_XR_FUNC(xrGetVulkanGraphicsRequirementsKHR) \
    USE_XR_FUNC(xrGetVulkanInstanceExtensionsKHR) \
    USE_XR_FUNC(xrGetWorldMeshBufferRecommendSizeML) \
    USE_XR_FUNC(xrHapticParametricGetPropertiesEXT) \
    USE_XR_FUNC(xrImportLocalizationMapML) \
    USE_XR_FUNC(xrLoadControllerModelMSFT) \
    USE_XR_FUNC(xrLoadRenderModelFB) \
    USE_XR_FUNC(xrLocateBodyJointsBD) \
    USE_XR_FUNC(xrLocateBodyJointsFB) \
    USE_XR_FUNC(xrLocateBodyJointsHTC) \
    USE_XR_FUNC(xrLocateGeospatialPoseANDROID) \
    USE_XR_FUNC(xrLocateGeospatialPoseFromPoseANDROID) \
    USE_XR_FUNC(xrLocateHandJointsEXT) \
    USE_XR_FUNC(xrLocateSceneComponentsMSFT) \
    USE_XR_FUNC(xrLocateSpace) \
    USE_XR_FUNC(xrLocateSpaces) \
    USE_XR_FUNC(xrLocateSpacesKHR) \
    USE_XR_FUNC(xrLocateSpatialContainerViewsEXT) \
    USE_XR_FUNC(xrLocateViews) \
    USE_XR_FUNC(xrNegotiateLoaderRuntimeInterface) \
    USE_XR_FUNC(xrPassthroughLayerPauseFB) \
    USE_XR_FUNC(xrPassthroughLayerResumeFB) \
    USE_XR_FUNC(xrPassthroughLayerSetKeyboardHandsIntensityFB) \
    USE_XR_FUNC(xrPassthroughLayerSetStyleFB) \
    USE_XR_FUNC(xrPassthroughPauseFB) \
    USE_XR_FUNC(xrPassthroughStartFB) \
    USE_XR_FUNC(xrPathToString) \
    USE_XR_FUNC(xrPauseSimultaneousHandsAndControllersTrackingMETA) \
    USE_XR_FUNC(xrPerfSettingsSetPerformanceLevelEXT) \
    USE_XR_FUNC(xrPersistAnchorANDROID) \
    USE_XR_FUNC(xrPersistSpatialAnchorAsyncBD) \
    USE_XR_FUNC(xrPersistSpatialAnchorCompleteBD) \
    USE_XR_FUNC(xrPersistSpatialAnchorMSFT) \
    USE_XR_FUNC(xrPersistSpatialEntityAsyncEXT) \
    USE_XR_FUNC(xrPersistSpatialEntityCompleteEXT) \
    USE_XR_FUNC(xrPollEvent) \
    USE_XR_FUNC(xrPollFutureEXT) \
    USE_XR_FUNC(xrPublishSpatialAnchorsAsyncML) \
    USE_XR_FUNC(xrPublishSpatialAnchorsCompleteML) \
    USE_XR_FUNC(xrQueryFramesPerBufferRangeBD) \
    USE_XR_FUNC(xrQueryLocalizationMapsML) \
    USE_XR_FUNC(xrQueryPerformanceMetricsCounterANDROID) \
    USE_XR_FUNC(xrQueryPerformanceMetricsCounterMETA) \
    USE_XR_FUNC(xrQuerySenseDataAsyncBD) \
    USE_XR_FUNC(xrQuerySenseDataCompleteBD) \
    USE_XR_FUNC(xrQuerySpacesFB) \
    USE_XR_FUNC(xrQuerySpatialAnchorsAsyncML) \
    USE_XR_FUNC(xrQuerySpatialAnchorsCompleteML) \
    USE_XR_FUNC(xrQuerySpatialComponentDataEXT) \
    USE_XR_FUNC(xrQuerySystemTrackedKeyboardFB) \
    USE_XR_FUNC(xrRaycastANDROID) \
    USE_XR_FUNC(xrReleaseSwapchainImage) \
    USE_XR_FUNC(xrRemoveTrackableImageDatabaseANDROID) \
    USE_XR_FUNC(xrRequestBodyTrackingFidelityMETA) \
    USE_XR_FUNC(xrRequestBoundaryVisibilityMETA) \
    USE_XR_FUNC(xrRequestDisplayRefreshRateFB) \
    USE_XR_FUNC(xrRequestExitSession) \
    USE_XR_FUNC(xrRequestMapLocalizationML) \
    USE_XR_FUNC(xrRequestSceneCaptureFB) \
    USE_XR_FUNC(xrRequestSpatialContainerBoundsModeEXT) \
    USE_XR_FUNC(xrRequestSpatialContainerVisibleEXT) \
    USE_XR_FUNC(xrRequestWorldMeshAsyncML) \
    USE_XR_FUNC(xrRequestWorldMeshCompleteML) \
    USE_XR_FUNC(xrRequestWorldMeshStateAsyncML) \
    USE_XR_FUNC(xrRequestWorldMeshStateCompleteML) \
    USE_XR_FUNC(xrResetBodyTrackingCalibrationMETA) \
    USE_XR_FUNC(xrResultToString) \
    USE_XR_FUNC(xrResultToString2KHR) \
    USE_XR_FUNC(xrResumeSimultaneousHandsAndControllersTrackingMETA) \
    USE_XR_FUNC(xrRetrieveSpaceQueryResultsFB) \
    USE_XR_FUNC(xrSaveSpaceFB) \
    USE_XR_FUNC(xrSaveSpaceListFB) \
    USE_XR_FUNC(xrSaveSpacesMETA) \
    USE_XR_FUNC(xrSendVirtualKeyboardInputMETA) \
    USE_XR_FUNC(xrSetColorSpaceFB) \
    USE_XR_FUNC(xrSetDigitalLensControlALMALENCE) \
    USE_XR_FUNC(xrSetEnvironmentDepthEstimationVARJO) \
    USE_XR_FUNC(xrSetFacialSimulationModeBD) \
    USE_XR_FUNC(xrSetGoogleCloudAuthAsyncANDROID) \
    USE_XR_FUNC(xrSetGoogleCloudAuthCompleteANDROID) \
    USE_XR_FUNC(xrSetHandTrackingFrequencyHintMETA) \
    USE_XR_FUNC(xrSetHdrMetadataSONY) \
    USE_XR_FUNC(xrSetInputDeviceActiveEXT) \
    USE_XR_FUNC(xrSetInputDeviceLocationEXT) \
    USE_XR_FUNC(xrSetInputDeviceStateBoolEXT) \
    USE_XR_FUNC(xrSetInputDeviceStateFloatEXT) \
    USE_XR_FUNC(xrSetInputDeviceStateVector2fEXT) \
    USE_XR_FUNC(xrSetMarkerTrackingPredictionVARJO) \
    USE_XR_FUNC(xrSetMarkerTrackingTimeoutVARJO) \
    USE_XR_FUNC(xrSetMarkerTrackingVARJO) \
    USE_XR_FUNC(xrSetPassthroughLayerMeshANDROID) \
    USE_XR_FUNC(xrSetPerformanceMetricsStateANDROID) \
    USE_XR_FUNC(xrSetPerformanceMetricsStateMETA) \
    USE_XR_FUNC(xrSetSpaceComponentStatusFB) \
    USE_XR_FUNC(xrSetSystemNotificationsML) \
    USE_XR_FUNC(xrSetTilePropertiesHintMETA) \
    USE_XR_FUNC(xrSetTrackingOptimizationSettingsHintQCOM) \
    USE_XR_FUNC(xrSetViewOffsetVARJO) \
    USE_XR_FUNC(xrSetVirtualKeyboardModelVisibilityMETA) \
    USE_XR_FUNC(xrShareSpacesFB) \
    USE_XR_FUNC(xrShareSpacesMETA) \
    USE_XR_FUNC(xrShareSpatialAnchorAsyncBD) \
    USE_XR_FUNC(xrShareSpatialAnchorCompleteBD) \
    USE_XR_FUNC(xrSnapshotMarkerDetectorML) \
    USE_XR_FUNC(xrStartBodyTrackingCalibrationAppBD) \
    USE_XR_FUNC(xrStartColocationAdvertisementMETA) \
    USE_XR_FUNC(xrStartColocationDiscoveryMETA) \
    USE_XR_FUNC(xrStartSenseDataProviderAsyncBD) \
    USE_XR_FUNC(xrStartSenseDataProviderCompleteBD) \
    USE_XR_FUNC(xrStopColocationAdvertisementMETA) \
    USE_XR_FUNC(xrStopColocationDiscoveryMETA) \
    USE_XR_FUNC(xrStopHapticFeedback) \
    USE_XR_FUNC(xrStopSenseDataProviderBD) \
    USE_XR_FUNC(xrStringToPath) \
    USE_XR_FUNC(xrStructureTypeToString) \
    USE_XR_FUNC(xrStructureTypeToString2KHR) \
    USE_XR_FUNC(xrSubmitSoundFieldBufferBD) \
    USE_XR_FUNC(xrSubmitSoundObjectBufferBD) \
    USE_XR_FUNC(xrSuggestBodyTrackingCalibrationOverrideMETA) \
    USE_XR_FUNC(xrSuggestInteractionProfileBindings) \
    USE_XR_FUNC(xrSuggestVirtualKeyboardLocationMETA) \
    USE_XR_FUNC(xrSyncActions) \
    USE_XR_FUNC(xrThermalGetTemperatureTrendEXT) \
    USE_XR_FUNC(xrTryCreateSpatialGraphStaticNodeBindingMSFT) \
    USE_XR_FUNC(xrUnpersistAnchorANDROID) \
    USE_XR_FUNC(xrUnpersistSpatialAnchorAsyncBD) \
    USE_XR_FUNC(xrUnpersistSpatialAnchorCompleteBD) \
    USE_XR_FUNC(xrUnpersistSpatialAnchorMSFT) \
    USE_XR_FUNC(xrUnpersistSpatialEntityAsyncEXT) \
    USE_XR_FUNC(xrUnpersistSpatialEntityCompleteEXT) \
    USE_XR_FUNC(xrUpdateHandMeshMSFT) \
    USE_XR_FUNC(xrUpdatePassthroughColorLutMETA) \
    USE_XR_FUNC(xrUpdateSoundFieldConfigBD) \
    USE_XR_FUNC(xrUpdateSoundObjectConfigBD) \
    USE_XR_FUNC(xrUpdateSoundObstacleConfigBD) \
    USE_XR_FUNC(xrUpdateSoundObstacleMaterialConfigBD) \
    USE_XR_FUNC(xrUpdateSpatialAnchorsExpirationAsyncML) \
    USE_XR_FUNC(xrUpdateSpatialAnchorsExpirationCompleteML) \
    USE_XR_FUNC(xrUpdateSwapchainFB) \
    USE_XR_FUNC(xrWaitAudioPeriodBD) \
    USE_XR_FUNC(xrWaitFrame) \
    USE_XR_FUNC(xrWaitSwapchainImage)

#endif /* __WINE_OPENXR_THUNKS_H */
/* For use by xrInstance and children */
struct openxr_instance_funcs
{
#define USE_XR_FUNC(x) PFN_ ## x p_ ## x;
    ALL_XR_INSTANCE_FUNCS()
#undef USE_XR_FUNC
};

