@ stdcall xrNegotiateLoaderRuntimeInterface(ptr ptr) wine_xrNegotiateLoaderRuntimeInterface
@ stdcall __wineopenxr_GetVulkanInstanceExtensions(ptr)
@ stdcall __wineopenxr_GetVulkanDeviceExtensions(ptr)
